### PR TITLE
Ask about vegetarian and vegan food at pubs

### PR DESCRIPTION
**Pull request by peternewman**
Untested but pretty trivial

### CODE REVIEW

**Review by westnordost — APPROVED** [review]

**Comment by westnordost** [comment]
makes sense, yeah

**Comment by peternewman** [comment]
Thanks. I did have a minor fear about no food pubs, but that doesn't match the ones I see.

I've not checked about Kosher, but would need to read up on Jews and alcohol to see if it's even relevant.

**Comment by westnordost** [comment]
Oh hmm, right, I didn't think about that. I only thought about "pub", as in Britain. But in Germany, `amenity=pub` are mostly "Kneipen", which are like bars for old people and/or smokers (feel like it). For most, there is no food.

Let's change that to only pubs that have `food=yes`.

**Comment by westnordost** [comment]
Though even though mentioned in the wiki, `food=*` is tagged on less than 0.5% of all pubs (because it doesn't show up in taginfo at all)

**Comment by peternewman** [comment]
> Oh hmm, right, I didn't think about that. I only thought about "pub", as in Britain. But in Germany, `amenity=pub` are mostly "Kneipen", which are like bars for old people and/or smokers (feel like it). For most, there is no food.

Aside from the no food bit, that pretty much matches a lot of British pubs too!

That also explains the contradictions all over the place in the wiki around whether pubs do or don't have food, it presumably depends which nationality wrote the text.

> Let's change that to only pubs that have `food=yes`.
> Though even though mentioned in the wiki, `food=*` is tagged on less than 0.5% of all pubs (because it doesn't show up in taginfo at all)

From memory we can't easily include or exclude particular query terms by country can we? Or with different queries by country?

I could propose the obvious food quest, but the tag seem to have limited usage currently...

**Comment by westnordost** [comment]
> From memory we can't easily include or exclude particular query terms by country can we? Or with different queries by country?

No

**Comment by westnordost** [comment]
The `food` tag is documented and seems to make sense. Maybe a quest could be added for that (I have already an icon for that! The beer icon!) but maybe... would you mind asking on the tagging mailing list if there are any reservations against using this tag? (as it is not really used yet)

**Comment by westnordost** [comment]
Or @matkoniecz, would you? I am not on the list (too much traffic, awkward/obsolete media format)

**Comment by peternewman** [comment]
> The `food` tag is documented and seems to make sense. Maybe a quest could be added for that (I have already an icon for that! The beer icon!)

Shouldn't that be saved for a draught beer quest or something more important? :smile: As well as possibly applying the food quest to other non-pub things in future?

> Or @matkoniecz, would you? I am not on the list (too much traffic, awkward/obsolete media format)

Seconded please, I'm not either.

**Comment by peternewman** [comment]
Do you want me to revert this for now or open a new PR which requires `food!=no` too for pub or wait and see about the tagging list?

**Comment by matkoniecz** [comment]
> Or @matkoniecz, would you? I am not on the list (too much traffic, awkward/obsolete media format)

Done! For "too much traffic" - I have a separate email account for that (used to have on my main one - was far too distracting)

**Comment by westnordost** [comment]
Thanks! Though, more important than what some people consider helpful or not, I'd find if the tag could be viewed in any way problematic. 

@peternewman I think for now it would be good to open a PR to only ask for pubs with food=yes. Would you do that?

**Comment by peternewman** [comment]
> @peternewman I think for now it would be good to open a PR to only ask for pubs with food=yes. Would you do that?

No problem, see #3099

**Comment by codeinabox** [comment]
> The `food` tag is documented and seems to make sense. Maybe a quest could be added for that (I have already an icon for that! The beer icon!)

I would love to see a quest asking if a bar or pub serves food, as in meals not bar snacks. Currently I have to add food=yes manually with another editor.

**Comment by matkoniecz** [comment]
You can propose a new quest ( https://github.com/streetcomplete/StreetComplete/issues/new?assignees=&labels=&template=quest-suggestion.md  via https://github.com/streetcomplete/StreetComplete/issues/ ) if it matches requirements.

(no idea about this specific case)

**Comment by peternewman** [comment]
@codeinabox for some background discussion on that sort of quest, see https://github.com/streetcomplete/StreetComplete/pull/3099 and https://github.com/streetcomplete/StreetComplete/issues/3408 .

The initial first challenge is agreeing what counts as food. But yes I'd certainly agree that this is annoying:

> Currently I have to add food=yes manually with another editor.

**Pull request merged**
