### PR TITLE
Check for grit bins every 4 years

### PR DESCRIPTION
**Pull request by arrival-spring**
4 years seems like a sensible frequency to check these
Clsoes #2726

### CODE REVIEW

**Comment by arrival-spring** [comment]
Closes #2726

**Comment by matkoniecz** [comment]
Looks obvious, but have you tested it?

**Comment by HolgerJeromin** [comment]
> Closes #2726

This needs to be in the first comment.

**Comment by arrival-spring** [comment]
In that it shows up for a grit bin near me that was last edited more than 5 years ago

**Comment by matkoniecz** [comment]
> In that it shows up for a grit bin near me that was last edited more than 5 years ago

Ideally you would also solve this quest and see in logs is it acting as expected (in this case bug in ridiculously unlikely but I found some when I tested "obvious" changes).

I see in logs `D/QuestController: Solved a CheckExistence quest: ADD "check_date"="2021-04-10"` and `D/QuestController: Deleted NODE #4029804614 in frame of quest CheckExistence` so it seems working as expected :)

**Pull request merged**
