### PR TITLE
Add Drinking Water Fee Quest

### PR DESCRIPTION
**Pull request by Arthur-GYT**
All is in the title ^^.

### CODE REVIEW

**Comment by matkoniecz** [comment]
In which areas drinkable water has decent chance to be paid? I never have seen one in Poland and Europe in general. And also in my (limited) trips outside Europe.

**Comment by westnordost** [comment]
Never seen that either... Also, arguably, if the water costs something, then the question is whether it should really be tagged as `drinking_water` rather than as a vending machine that sells water.

**Comment by Helium314** [comment]
I also never saw a paid drinking water... thing, but according to taginfo, 1% of all `amenity=drinking_water` is tagged with `fee=yes`

**Comment by Helium314** [comment]
A good portion of the paid ones seem to be indoor or near caravan sites

**Comment by matkoniecz** [comment]
> indoor or near caravan sites

and probably should be `access=customers` instead

**Comment by matkoniecz** [comment]
There is another class: mineral water similar to https://uzdrowisko-iwonicz.com.pl/pijalnia-wod-mineralnych/ but these are exceedingly rare

**Pull request closed without merging**
