### PR TITLE
Remove allowbackup=false

### PR DESCRIPTION
**Pull request by tiziodcaio**
So you allow backups and we can use with seedvault

### CODE REVIEW

**Comment by matkoniecz** [comment]
have you seen reasoning in https://github.com/streetcomplete/StreetComplete/commit/611005bd3e4ebd0cffc9e5f117c3920ff13eecdd ?

And #3030 ?

**Comment by Cj-Malone** [comment]
Having just set up a new phone, I'd have liked my enabled quests transferred. Theoretically if I had both phones at the same time I could have done the new preset share, but that's not ideal.

**Comment by westnordost** [comment]
Is it possible to select programmatically what gets backed up and what does not? Because as written before, there is a certain maximum cloud backup size (local backup is kind of rather for the technical affine users who could just as well copy from the filesystem) which is easily exceeded by any one quest download.

**Comment by mnalis** [comment]
> Theoretically if I had both phones at the same time I could have done the new preset share, but that's not ideal.

Workaround: Even if you don't have both phones at the same time, you can click that "copy" button, and then paste the links in some text file (or send yourself an email or whatever), and then import quest by opening that link on a new phone later. (but yes, I agree it's not terribly efficient, especially if you have multiple presets. Then again, one probably doesn't changes phone too often). 

I don't know about android internals on how to make it automatic, but in docs there seems to be section called  [Include and exclude files](https://developer.android.com/guide/topics/data/autobackup#IncludingFiles) which might help this PR to include only user settings and presets, and exclude other stuff (quests should probably be uploaded before transitioning to new phone, or that might make backup more complicated)

**Comment by westnordost** [comment]
Hm well, currently, all is saved in the one shared pref file + the database (which is also a file). There is no distinction made between data that should be kept when moving to a new phone and data that should not be kept. This would require having two database files and deciding for each table in which it should go.
The same with the shared preferences.

I am not really opposed to this, as long as it can be implemented without a lot of code. However, this would be the prerequisite to enable backup, IMO.

**Comment by westnordost** [comment]
Anyway, I will close this. Feel free to create a new PR if the above can be implemented with a reasonable amount of code.

**Pull request closed without merging**
