### PR TITLE
Add Bus Stop Lit quest

### LINKED ISSUE #2383: Is this bus stop well lit or has a light?
### General
Affected tag(s) to be modified/added: [lit](https://wiki.openstreetmap.org/wiki/Key:lit)
Question asked: **Is this bus stop well lit or has a light?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

We currently don't have a quest for lights on a bus stop. In remote areas there are lights on the bus stops and the intersections, but not on the street itself. 

At night you might feel a bit more comfortable waiting on a well lit bus stop, than in pitch darkness. So there's one possible usecase for the data.

### PR DESCRIPTION
**Pull request by TurnrDev**
Fixes #2383 

Based on #2737 as I'm new to this.

### CODE REVIEW

**Comment by TurnrDev** [comment]
[Tested and working](https://www.openstreetmap.org/changeset/104143269)

**Comment by matkoniecz** [comment]
New icon may be nice, maybe some combo of lit quest icon and bus? Like tactile pavings for bus stop?

**Review by matkoniecz — APPROVED** [review]

**Comment by TurnrDev** [comment]
> New icon may be nice, maybe some combo of lit quest icon and bus? Like tactile pavings for bus stop?

I agree. I've not figured out how to make the icons yet so I'll leave that up to @westnordost if they want to implement that :)

**Comment by westnordost** [comment]
Sure, will do this. Though it will take some time until this is merged because new quests are only added for each major version and the major version is already in alpha.

**Comment by westnordost** [comment]
Oh damn, I also merged that other PR that had string changes. Oh well, then this will be included in v32

**Comment by TurnrDev** [comment]
> Oh damn, I also merged that other PR that had string changes. Oh well, then this will be included in v32

Haha sweet! I was willing to wait, but this is even better news!

**Comment by westnordost** [comment]
I'll do the icon after the merge

**Comment by westnordost** [comment]
bus_stop_name

Uninspired, but 
image

**Pull request merged**
