### PR TITLE
OpenStreetCam rebranded as KartaView

### PR DESCRIPTION
**Pull request by matkoniecz**
Description has no need for change.

Not sure whatever change id or keep it the same (what is the impact here?).

Not sure whatever https://kartaview.org/map/ or https://kartaview.org is preferable

Logo also needs to be updated.

### CODE REVIEW

**Comment by westnordost** [comment]
Current impact is none, because it is not included in any achievement. Thank you for the info, I'll replace it real quick

**Comment by matkoniecz** [comment]
> it is not included in any achievement.

Maybe it would fit thematically achievement car? Most people contributing have it in their car, AFAIK.

**Comment by westnordost** [comment]
Mh yeah, maybe it would. You can create a PR for that if you like

**Comment by matkoniecz** [comment]
OK, I will wait for a new id.

**Pull request closed without merging**
