### PR TITLE
Ask for name, opening hours, wheelcair access for some `healthcare` tags

### PR DESCRIPTION
**Pull request by FloEdelmann**
All of them are included in https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/assets/osmfeatures/default/de.json, so translations should be fine. I haven't checked other languages though.

### CODE REVIEW

**Comment by matkoniecz** [comment]
Any reason why `"sample_collection", "blood_donation", "physiotherapist", "podiatrist",` are excluded from wheelchair quest?

I would skip  `"laboratory"` - it can be used according to its definition to internal features not accessible at all (often `healthcare=sample_collection` are marked as laboratories - or to be more specific there was not even a tagging for them before https://wiki.openstreetmap.org/wiki/Proposed_features/healthcare%3Dsample_collection ).

`healthcare=laboratory` + `sample collection=yes` indicates that it is publicly accessible but it is barely used.

Hmmmm. Maybe quest for `healthcare=laboratory` which would add `sample collection=yes` or `sample collection=no` or retag to `healthcare=sample_collection` would be a good idea? (disclaimer: I invented this tags and wrote most of https://wiki.openstreetmap.org/wiki/Proposed_features/healthcare%3Dsample_collection )

**Comment by FloEdelmann** [comment]
For `physiotherapist` and `podiatrist`, it might be difficult to determine if they can actually treat wheelchair patients.

For `sample_collection` and `blood_donation`, there is no real reason. I'll add them.

> often `healthcare=sample_collection` are marked as laboratories

That's why I added them. If you think it will be difficult to determine there, I'll remove it though.

> Maybe quest for `healthcare=laboratory` which would add `sample collection=yes` or `sample collection=no` or retag to `healthcare=sample_collection` would be a good idea?

If they can be "internal features not accessible at all", then it's probably not a good idea. Additionally, I think that determining "yes" is probably mostly easy, but "no" will often be much harder.

**Comment by matkoniecz** [comment]
Looks great to me, though I have not tested code in action so far.

**Review by westnordost — APPROVED** [review]
Looks like a good addition, thank you!

**Pull request merged**
