### PR TITLE
add acrylic surface

### LINKED ISSUE #5965: Add surface=acrylic option for sports pitches
### General
Affected tag(s) to be modified/added: [leisure=pitch](https://wiki.openstreetmap.org/wiki/Key:leisure), [surface=acrylic](https://wiki.openstreetmap.org/wiki/Tag:surface%3Dacrylic)
Question asked: The question is already asked as **What's the surface here?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** Already implemented

**Metadata needed:** Not sure, common in the U.S.

**Proposed UI:** Add surface=acrylic to the list of options available when selecting the surface of a `leisure=pitch` element

**Notes**: Adding this as a "Quest suggestion", because it didn't seem like a feature or bug.

I'm a little vague on how to tag certain sports pitches, notably tennis courts and some basketball courts. I've inspected them while using StreetComplete, and I've left the quests unsolved for now. From what I can tell, the surfaces are acrylic, with concrete or asphalt underneath. It's hard to tell for sure without being an expert, but that's what visual inspection and the internet seem to think.

If there's another option that should be used instead like `surface=paved`, it would be good if StreetComplete could guide users towards that option. You can enter that, but it shows up as "Paved (generic)", which seems like it's a less-specific option, with a picture that is just bare concrete/asphalt. If that's the preferred option, maybe StreetComplete could change the input for `leisure=pitch` to show a different picture when answering `surface=*`?

Here's an example of a tennis court currently tagged as `surface=paved`, but should be tagged as `surface=acrylic` AFAICT:

https://www.openstreetmap.org/way/39153147

Here's an example of a tennis court tagged with `surface=acrylic`:

https://www.openstreetmap.org/way/362822900

[leisure=pitch taginfo](https://taginfo.openstreetmap.org/tags/leisure=pitch#combinations) doesn't show any results for combinations with `surface=acrylic` for some reason, even though it's more common than some of the tags shown

### PR DESCRIPTION
**Pull request by westnordost**
Fixes #5965

### CODE REVIEW

**Comment by westnordost** [comment]
I also changed it so that the "rubber granules" option tags `surface=rubber` instead of `surface=tartan`. Do you think this is an improvement?

**Comment by matkoniecz** [comment]
I am trying to figure out is this soft merged granule surface a rubber or not. Failed so far.

**Comment by westnordost** [comment]
Well, it's certainly not *natural* rubber, but neither is the rubbery surface on playgrounds etc (`surface=rubber`) nor are "rubber" tyres.

https://en.wikipedia.org/wiki/Tartan_track by 3M specifically is polyurethane according to that article, but that doesn't mean that tracks made from rubbery granules from other manufacturers couldn't be made from other materials.

What they have in common is that they are, well bound rubber(y) granules.

The wiki states that `surface=rubber` may also be loose rubber granules, solid rubber (and bound rubber granules paving plates), but not sure if any of these is actually a thing. In any case, that tag is defined more widely.

**Comment by knkski** [comment]
Thanks for handling this! This looks like it will help the clarity of the quest by a lot.

**Pull request merged**
