### PR TITLE
[WIP] What kind of memorial is this?

### LINKED ISSUE #1572: What kind of memorial is this
### General
Affected tag(s) to be modified/added: [Memorial](https://wiki.openstreetmap.org/wiki/Tag:historic%3Dmemorial)
Question asked: **What kind of Memorial is this?**
- memorial=war_memorial - war memorial
- memorial=plaque - Commemorative plaque
- memorial=blue_plaque - mainly in UK. See Blue plaque
- memorial=statue - statue (personage/animal) Statue
- memorial=bust - bust
- memorial=sculpture - non figurative sculpture
- memorial=stele - stele
- memorial=obelisk - obelisk - Small ones only for others see historic=monument and man_made=obelisk
- memorial=stone - block of stone used as support.
- memorial=stolperstein - Stolperstein - almost not in use.
- memorial=cross - memorial cross - Do not confuse with historic=wayside_cross and man_made=cross
- memorial=ghost_bike - a white bicycle to remember cyclists who died in traffic accidents.

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### PR DESCRIPTION
**Pull request by kmpoppe**
Closes #1572.

For the first throw, I've selected the entries, that have a wiki page, that are in the most used on taginfo AND that I could find pictures for that are either Public Domain or CC0.

Soruces are as follows:
`memorial=statue`:
https://commons.wikimedia.org/wiki/File:George_Washington_statue_in_the_Boston_Public_Garden_-_DSC08196.JPG
`memorial=bust`:
https://commons.wikimedia.org/wiki/File:Aristotelis_Valaoritis_bust_National_Garden_Athens,_Greece.jpg
`memorial=plaque`:
https://commons.wikimedia.org/wiki/File:Bleaklow_Plaque.jpg
`memorial=stolperstein`:
https://flic.kr/p/2jLQ3Xc
`memorial=stone`:
https://commons.wikimedia.org/wiki/File:Memorial_stone_of_battle_of_Liljendal.18080224.ojp.JPG
`memorial=war_memorial`:
https://commons.wikimedia.org/wiki/File:Women_of_World_War_II.jpg

Please comment on the pictures if anyone wants me to change something.

Reasons for leaving out others:
* `memorial=blue_plaque`- mainly in the UK, only around 370 uses. There might be a nice way of filtering whether the quest is being solved at a place in the UK and then display that option, but we'd still need to figure the licensing issue for a picture. There seems to be something special about them, haven't figured it out completely.
* `memorial=sculpture` and `memorial=cross` - no wiki pages, less than 1k uses
* `memorial=stele` and `memorial=obelisk` - quite frankly, I was unable to find pictures that made a distinction clear on first look. My (not so much-)favourite was a (not PD or CC0) picture in the German Wikipedia article about steles, that showed three stone blocks shaped like a small obelisk... not helpful.
* `memorial=ghost_bike` - 160 uses, heavily used only in Germany and the Netherlands, rest of the world: USA 21, South America: 3, EU/Turkey w/o GER and NLD: 25 - Yes, it warrants a wiki-page due to the importance of the subject, but I don't think it's that useful in SC.

Bonus feature that I'd love to do (@westnordost, can you advise if possible): If the user selects `war_memorial` ask them what conflict (`memorial:conflict`) it's for.

Comments welcome.

### CODE REVIEW

**Comment by matkoniecz** [comment]
> either Public Domain or CC0.

Note that other permissive licenses are also allowed (roughly, if image can be uploaded to Wikimedia Commons then it can also be used here - see for example https://github.com/westnordost/StreetComplete/blob/master/app/src/main/res/authors.txt )

BTW, updating https://github.com/westnordost/StreetComplete/blob/master/app/src/main/res/authors.txt would be part of a final PR

**Comment by matkoniecz** [comment]
> `statue` (...) `war_memorial`

How war memorial statue should be answered?

**Comment by kmpoppe** [comment]
> Note that other permissive licenses are also allowed (roughly, if image can be uploaded to Wikimedia Commons then it can also be used here - see for example https://github.com/westnordost/StreetComplete/blob/master/app/src/main/res/authors.txt )

I was under the impression, that CC BY SA and the likes didn't allow altering (I was mistaken) so I didn't think of them as croppable to a square. 

> BTW, updating https://github.com/westnordost/StreetComplete/blob/master/app/src/main/res/authors.txt would be part of a final PR

Yep, I overlooked that.

**Comment by matkoniecz** [comment]
> CC BY SA and the likes didn't allow altering

Note that depends on version. CC licences range from restrictive (NC-ND version) to quite permissive.

**Comment by kmpoppe** [comment]
> How war memorial statue should be answered?

Now that would be a problem not specific to us, but rather a general problem with tagging, right? My take on this, when working with SC or in general, the more specific my impression of a thing is the more I learn to tagging this. Like, all `war_memorial`s in a form of a statue of a person or similar are also `statue`s, but not all statues are war memorials.

My hope in this would be, that the user reads all the options available and then picks the most specific that fits here. Is that assumption wrong for the majority of users?

**Comment by matkoniecz** [comment]
> Now that would be a problem not specific to us, but rather a general problem with tagging, right?

Yes, but "tagging some situation is impossible / extremely complicated / hopelessly confusing" may be blocker for SC quests (and this specific problem is why I decided to implement something else).

**Comment by kmpoppe** [comment]
¯\_(ツ)_/¯ I don't find that particularly confusing, but that might just be me.

**Review by westnordost — CHANGES_REQUESTED** [review]
Implementation looks fine. See @matkoniecz 

I see a few issues with the selections:
- where exactly is the difference between a blue plaque and a plaque and why does it matter? Also, where is the difference to `tourism=information + information=board + board_type=history` ?
- since a memorial is simply an artwork (`tourism=artwork`) but with a memorial function, we might need to look into [`artwork_type`](https://taginfo.openstreetmap.org/keys/artwork_type#values) whether there are any values that should also be selectable

Comments on the pictures:
- `statue` needs to be changed. The whole statue or at least most of it should be visible
- `bust` is okay. Maybe it would be a little better to show a bit more of the pedestal so that it is clear that it's only a bust and not a picture of a cropped statue
- for `stolperstein`, it would be helpful to see it in context, i.e. see it as one stone in the pavement rather than being able to read exactly who has been murdered. Not everyone knows what a stolperstein is and might then have the wrong idea how big it is or where to search for it when asked this question. In other words, without the context (it is a stone in the pavement), people might answer "there is no memorial here"
- `war memorial` is fine, I think this is a good example and clearly distinct

---

Also, you need to add the SVG into the /res/quest icons/ directory.

**Comment by westnordost** [comment]
@matkoniecz the way I see it, there is an easy distinction: If the memorial shows a particular person, that's a statue. If it for example shows an unnamed starved out prisoner of war, it's a war memorial. You remember this memorial?

https://www.openstreetmap.org/node/3858621969#map=18/53.19437/13.15191

For me, this is clearly a war memorial. Though ironically, it has been tagged as statue. So I guess there are different opinions on this.

**Comment by kmpoppe** [comment]
>     * where exactly is the difference between a blue plaque and a plaque and why does it matter? Also, where is the difference to `tourism=information + information=board + board_type=history` ?
.
Just a quick answer while outside; Blue Plaque is a fixed term in the UK. Their production and dedication follows specfic rules. Someone looking for them on OSM wouldn't look for `memorial=plaque+colour=blie`, because that simply isn't specific enough.

Also, for me, the distinction between historic tourism boards would be who erected them and where. A tourism board comes from the governmental tourism body of any place, where a general plaque can also be from any private or volunteer group. Again, this is my interpretation only that I use when mapping, this might be different for others.

**Comment by kmpoppe** [comment]
> Also, you need to add the SVG into the /res/quest icons/ directory.

Excuse my idiocy, but what are the SVGs used for? They're just in use outside of the app, right? Because just having the VD sitting in /app/src/main/res/drawable seemed totally fine.

> BTW, updating https://github.com/westnordost/StreetComplete/blob/master/app/src/main/res/authors.txt would be part of a final PR

It seems there's no alphabetical order in that file, shall I correct that in the same run?

**Comment by matkoniecz** [comment]
> Excuse my idiocy, but what are the SVGs used for? They're just in use outside of the app, right? Because just having the VD sitting in /app/src/main/res/drawable seemed totally fine.

One obvious use is that taking SVG, modifying it in Inkscape and importing it again is relatively easy. Editing imported drawable is more complicated (AFAIK it is in some weird format).

So main purpose would be making future changes or reuse of graphics easier.

**Comment by matkoniecz** [comment]
> It seems there's no alphabetical order in that file, shall I correct that in the same run?

If it would be done I would 

(a) do it in a separate commit
(b) keep separation into groups

Maybe there is some logic in group order, but I do not see it.

**Comment by kmpoppe** [comment]
> One obvious use is that taking SVG, modifying it in Inkscape and importing it again is relatively easy. Editing imported drawable is more complicated (AFAIK it is in some weird format, it can be reversed back to standard SVG but it is not trivial or obvious).

I've used shapesifter.design to format SVG back and forth with VDs, but I'm totally fine with that, if it makes life easier for other authors :-)

**Comment by kmpoppe** [comment]
PR comment update to new picture sources, new pictures checked in, SVG in quest icons, Translation to German.

**Comment by matkoniecz** [comment]
> Translation to German.

Translations are done in POEditor and will be overwritten, so adding them in PRs is not the best idea ( https://github.com/westnordost/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app )

**Comment by westnordost** [comment]
> Bonus feature that I'd love to do (@westnordost, can you advise if possible): If the user selects war_memorial ask them what conflict (memorial:conflict) it's for.

Doesn't seem to be documented. Looking at taginfo, my first answer would be "no", too free-form. But you can create a new issue and we can look deeper into that

Here's what still seems to be to do:
1. remove `blue_plaque` pictures because they are not used
2. add `obelisk` and `stele` because both are used really often. You can use pictures with the following cc licenses: CC-BY, CC-BY-SA, CC-0. The pictures from the wiki would be fine. Especially the picture for `obelisk` is good, because it shows that it does not need to be a huge thing like for example [the one in Istanbul](https://en.wikipedia.org/wiki/Obelisk_of_Theodosius) to be an obelisk.
3. it would be really good to have better pictures for `statue` and `stolperstein`, see my previous comment

**Comment by westnordost** [comment]
Also, would you be mad if I re-made the icon?

**Comment by kmpoppe** [comment]
> Doesn't seem to be documented. Looking at taginfo, my first answer would be "no", too free-form. But you can create a new quest suggestion and we can look deeper into that.

Ok, moving ToDo to a new quest
 
> 1. remove `blue_plaque` pictures because they are not used

Done

> 2. add `obelisk` and `stele` because both are used really often. You can use pictures with the following cc licenses: CC-BY, CC-BY-SA, CC-0. The pictures from the wiki would be fine. Especially the picture for `obelisk` is good, because it shows that it does not need to be a huge thing like for example [the one in Istanbul](https://en.wikipedia.org/wiki/Obelisk_of_Theodosius) to be an obelisk.

Ok, will do in the coming days.

> 3. it would be really good to have better pictures for `statue` and `stolperstein`, see my previous comment

I replaced them a few hours ago I thought?

**Comment by kmpoppe** [comment]
> Also, would you be mad if I re-made the icon?

Of course not, it was my first try in doing an icon and that was the best I could do. If you have anything better, please just commit them to my branch (should be editable by you)

**Comment by westnordost** [comment]
> I replaced them a few hours ago I thought:

Sorry, didn't notice

**Comment by peternewman** [comment]
>     * `memorial=blue_plaque`- mainly in the UK, only around 370 uses. There might be a nice way of filtering whether the quest is being solved at a place in the UK and then display that option, but we'd still need to figure the licensing issue for a picture. There seems to be something special about them, haven't figured it out completely.

Looks like there are 960 official ones in Greater London: https://en.wikipedia.org/wiki/List_of_English_Heritage_blue_plaques_in_London
Image (is this licence not suitable): https://en.wikipedia.org/wiki/File:Ian_Fleming_-_22_Ebury_Street_Blue_Plaque.jpg

In other countries, but I don't know if it should be flagged as a blue plaque there:
https://en.wikipedia.org/wiki/Blue_plaque#In_other_countries

@rjw62 could even do another of his pages to check they're all tagged:
https://en.wikipedia.org/wiki/List_of_English_Heritage_blue_plaques_in_London

>     * where exactly is the difference between a blue plaque and a plaque and why does it matter? Also, where is the difference to `tourism=information + information=board + board_type=history` ?

It's a specific type of plaque @westnordost . There are lots of others available but they aren't part of a set. Yes it probably should have been tagged as plaque:type=blue_plaque, but we are where we are with the tagging. A history information board would have far more detail, this is just one line with a name and a date.

Surely by the same argument a stolperstein is just a plaque on the floor?

> Bonus feature that I'd love to do (@westnordost, can you advise if possible): If the user selects `war_memorial` ask them what conflict (`memorial:conflict`) it's for.

Would that not want to be a separate quest anyway, then it could tidy up existing ones which are tagged without a conflict?

**Comment by westnordost** [comment]
> Surely by the same argument a stolperstein is just a plaque on the floor?

Probably, yes. Stolperstein should probably only be shown in Germany.

**Comment by westnordost** [comment]
Or actually, maybe even remove the `stolperstein` option. Rationale: Someone meaning to add a stolperstein will usually already have added `historic=memorial + memorial:type=stolperstein` because he wanted to specifically add a stolperstein, not "some" memorial.

Or in other words, of the memorials that do not have their memorial type added, it is **very unlikely** that there are any stolpersteins amongst these. I think most untagged ones will be some steles, obelisks or other sculptures.

Same argumentation for blue plaques. If someone wanted to add a blue plaque, he would already tag it like that and not add "some" memorial when he meant to add a blue plaque.

**Comment by westnordost** [comment]
What do you think, @kmpoppe ?

**Comment by kmpoppe** [comment]
Yep, let's throw out the stolperstein completely.
The obelisk picture from the OSM Wiki is ok, what do you think about https://de.wikipedia.org/wiki/Stele#/media/Datei:Visbek_Gerbert-Castus-Kreisel.jpg for stele?

**Comment by peternewman** [comment]
> > Surely by the same argument a stolperstein is just a plaque on the floor?
> 
> Probably, yes. Stolperstein should probably only be shown in Germany.

I'd assume it might be in a few surrounding countries too?

> Or actually, maybe even remove the `stolperstein` option. Rationale: Someone meaning to add a stolperstein will usually already have added `historic=memorial + memorial:type=stolperstein` because he wanted to specifically add a stolperstein, not "some" memorial.
> 
> Or in other words, of the memorials that do not have their memorial type added, it is **very unlikely** that there are any stolpersteins amongst these. I think most untagged ones will be some steles, obelisks or other sculptures.
> 
> Same argumentation for blue plaques. If someone wanted to add a blue plaque, he would already tag it like that and not add "some" memorial when he meant to add a blue plaque.

It didn't take too long to find a counter-example (particularly interesting given the commit message; it's not me before you ask :laughing: ):
https://www.openstreetmap.org/node/7959739857
https://www.english-heritage.org.uk/visit/blue-plaques/thomas-carlyle/
http://openplaques.org/plaques/216

This is actually a blue plaque despite not being blue!

https://en.wikipedia.org/wiki/Blue_plaque#English_Heritage_scheme
> Yep, let's throw out the stolperstein completely.

I'd agree they're least likely so should be at the bottom of their respective lists, but it seems a shame if it won't be possible to correctly improve the tagging of these in their respective countries. Or having to faff about leaving a note and updating it when you get home.

**Comment by westnordost** [comment]
@kmpoppe Yes, fair enough. I guess it is incredibly hard to find a "representative" stele. What also crossed my mind, since we (plan to) slash blue plaques and stolpersteins because they are unlikely to not be tagged already, is that maybe we shoud include sculpture for the same reason: Craft mappers tend to not tag the subtype if they cannot really classify it given the options in the wiki. So, many of those that are untagged may be more or less just some kind of generic sculptures that are neither statue, nor stele nor obelisk. I might have tagged your stele example as sculpture (or left out the subtype). So, sculpture would be a bit of a catch-all for when it does not have a clearly defined shape.

**Comment by westnordost** [comment]
I merged current master, was a bit more involved

**Comment by naposm** [comment]
> I'd assume it might be in a few surrounding countries too?

I can confirm, there are some in almost every major city here in Italy, they are called _[pietre d'inciampo](https://it.wikipedia.org/wiki/Pietre_d%27inciampo)_ and they are getting more and more popular.

**Comment by FloEdelmann** [comment]
@kmpoppe What's the state of this PR? Do you plan on finishing it sometime? Can somebody else take over? If so, what is done and what is left to do?

Please don't feel rushed or anything, I just want to help getting this PR finished.

**Comment by westnordost** [comment]
It looks like it is abandoned. I did add the "help wanted" label in case there is anyone who would like to bring this PR to completion, if I remember correctly, there was not that much that was missing.

**Comment by kmpoppe** [comment]
Hello guys,

as you've seen from my other comments, I did not abandon SC or OSM at all. As we all know, life happens sometimes and you don't get around to things again - especially with my added workload through C19. 

Once I return from holiday I'll get back to checking what the consensus on the way forward was and get back to this WIP.

Thanks for your patience.

K

**Comment by matkoniecz** [comment]
@kmpoppe Are you still planning to work on it?

There were some changes to quest syntax like #3647 and I can help applying them but not sure is this specific pull request still alive

**Comment by kmpoppe** [comment]
Hi @matkoniecz - the be perfectly honest, I will not come around to making this PR work in a foreseeable time, mostly because getting meaningful images took more challenging than expected.

Please close the PR, if I get around to making this work during the coming year, I'll simply create a new PR.

Thx!

Kai

**Comment by matkoniecz** [comment]
> getting meaningful images took more challenging than expected

I just want to say that it is normal, in quest requiring images about 80-90% of effort for me is hunting for images or making them.

**Comment by naposm** [comment]
Which are the photos needed, `stolperstein` and `statue`?

**Comment by FloEdelmann** [comment]
@naposm `stolperstein` is not needed anymore, see https://github.com/streetcomplete/StreetComplete/pull/2115#issuecomment-700622438.

**Comment by naposm** [comment]
> @naposm `stolperstein` is not needed anymore, see [#2115 (comment)](https://github.com/streetcomplete/StreetComplete/pull/2115#issuecomment-700622438).

Then I can help with `statue`, there plenty in my area, just let me know if you still need it. I can show some, then I can just take a photo myself so we can avoid copyright issues.

**Comment by matkoniecz** [comment]
> copyright issues

In which country you live? How old are statues? Note https://commons.wikimedia.org/wiki/Commons:Freedom_of_panorama issues.

And taking a fitting/finding photo (clearly visible as a statue, not confusing, good visibility in tiny image, no distraction, space in lower part of photo for label) would be useful even if this specific PR is dead.

Uploading to https://commons.wikimedia.org/ would be the best. Also, they have decent Android app.

**Comment by naposm** [comment]
Italy (the worst basically), but we have statues hundreds of years old, I think they can be photographed...

I can find them on Wikimedia Commons if needed, I think there are photos better than mine of such statues.

**Comment by matkoniecz** [comment]
> Italy (the worst basically), but we have statues hundreds of years old, I think they can be photographed...

Yes, if author died over 71 years ago then it is safe ( https://en.wikipedia.org/wiki/List_of_countries%27_copyright_lengths ).

> I think there are photos better than mine of such statues

This is also 100% fine! If you find something feel free to put a link here

**Comment by naposm** [comment]
> > Italy (the worst basically), but we have statues hundreds of years old, I think they can be photographed...
> 
> Yes, if author died over 71 years ago then it is safe ( https://en.wikipedia.org/wiki/List_of_countries%27_copyright_lengths ).

I think they did...

> > I think there are photos better than mine of such statues
> 
> This is also 100% fine! If you find something feel free to put a link here

Perfect, added one just now!

**Comment by matkoniecz** [comment]
> This one for example: https://commons.wikimedia.org/wiki/File:Napolo,_statuo_Umberto_1-a,_3.jpeg

This may be not suitable for nearly square or square images

> Also: https://commons.wikimedia.org/wiki/File:Vittorio_Emanuele_II_statua_Piazza_Bovio_Napoli_D.jpg

Quite busy background.

Likely second would be usable but if you find something with less busy background it would be great!

**Comment by naposm** [comment]
> Quite busy background.
> 
> Likely second would be usable but if you find something with less busy background it would be great!

I agree what do you think of those:
https://commons.wikimedia.org/wiki/File:Piazza_Dante._9498.jpg
https://commons.wikimedia.org/wiki/File:Statua_di_Dante4_(Naples).jpg

**Comment by naposm** [comment]
Great would be happy to see part of my city in the app!

**Comment by matkoniecz** [comment]
remaining things to do:

> Or actually, maybe even remove the `stolperstein` option. Rationale: Someone meaning to add a stolperstein will usually already have added `historic=memorial + memorial:type=stolperstein` because he wanted to specifically add a stolperstein, not "some" memorial.

> add obelisk and stele because both are used really often. You can use pictures with the following cc licenses: CC-BY, CC-BY-SA, CC-0. The pictures from the wiki would be fine. Especially the picture for obelisk is good, because it shows that it does not need to be a huge thing like for example [the one in Istanbul](https://en.wikipedia.org/wiki/Obelisk_of_Theodosius) to be an obelisk.

https://commons.wikimedia.org/wiki/File:Wolf-katharina-2008.jpg - there can be a problem with cropping it, but lets see

https://wiki.openstreetmap.org/wiki/Tag:memorial%3Dstele
https://wiki.openstreetmap.org/wiki/File:Infostele_Chronik_der_Mauer_mit_Adolph_Philipp.JPG - also there could be a cropping issue

--------------------------------------------

This PR includes icon made by westnordost - https://github.com/streetcomplete/StreetComplete/pull/2115/commits/90eb44b3f6a7559e147c0e22f69d68094692b49e (is it already on master branch of StreetComplete? If not - copy it there)

Sources for found images are as follows:

`memorial=statue`:
https://commons.wikimedia.org/wiki/File:Statua_di_Dante4_(Naples).jpg and https://commons.wikimedia.org/wiki/File:Garibaldi_Monument.jpg (NOT in this PR yet)
`memorial=bust`:
https://commons.wikimedia.org/wiki/File:Aristotelis_Valaoritis_bust_National_Garden_Athens,_Greece.jpg
`memorial=plaque`:
https://commons.wikimedia.org/wiki/File:Bleaklow_Plaque.jpg
`memorial=stolperstein`:
https://flic.kr/p/2jLQ3Xc https://commons.wikimedia.org/wiki/File:Memorial_type_stolperstein_source_(50390415497).jpg
`memorial=stone`:
https://commons.wikimedia.org/wiki/File:Memorial_stone_of_battle_of_Liljendal.18080224.ojp.JPG
`memorial=war_memorial`:
https://commons.wikimedia.org/wiki/File:Women_of_World_War_II.jpg

**Comment by matkoniecz** [comment]
> > How war memorial statue should be answered?
> @matkoniecz the way I see it, there is an easy distinction: If the memorial shows a particular person, that's a statue. If it for example shows an unnamed starved out prisoner of war, it's a war memorial. You remember this memorial?
> https://www.openstreetmap.org/node/3858621969#map=18/53.19437/13.15191
> For me, this is clearly a war memorial. Though ironically, it has been tagged as statue. So I guess there are different opinions on this.

I opened https://wiki.openstreetmap.org/wiki/Talk:Key:memorial#war_memorial_statue%2Fstele%2Fstone

**Comment by matkoniecz** [comment]
revived in https://github.com/streetcomplete/StreetComplete/pull/4102

**Pull request closed without merging**
