### PR TITLE
Visualize downloaded area

### PR DESCRIPTION
**Pull request by westnordost**
fixes the other thing for #4970

Turned out to be relatively straightforward after all. The further you zoom out, the less visible the hatching will be.

When one is zoomed out very far when the app initializes the map, I could reproduce that the entire world is hatched, even the downloaded tiles. The display is only updated after one downloads a tile or tabs out of the app and in again. I checked, it is definitely not an issue with the data but apparently with the rendering 🤷 
Not sure what to do about that. But otherwise, it works.

Screenshot_20230502_220341
Screenshot_20230502_220009
Screenshot_20230502_220126
Screenshot_20230502_220158
Screenshot_20230502_220213

### CODE REVIEW

**Comment by Helium314** [comment]
I didn't test, but does this show that nothing is downloaded when exiting team mode? (because then `removeAll` is called)

**Comment by westnordost** [comment]
Yes

**Comment by westnordost** [comment]
But yeah, that's not so nice. I'll make it so that instead of `removeAll`, the download time is set to 0, so it is always considered out of date.

**Comment by westnordost** [comment]
Done.

**Comment by westnordost** [comment]
Also, worked around that tangram bug

**Comment by Helium314** [comment]
> But yeah, that's not so nice. I'll make it so that instead of `removeAll`, the download time is set to 0, so it is always considered out of date.

Thanks!
(At some point I had tried to show a warning in SCEE when creating nodes and notes outside the downloaded area, but often got seemingly incorrect warnings because tiles had been removed.)

**Pull request merged**
