### PR TITLE
Add smichel17 to codeowners

### PR DESCRIPTION
**Pull request by smichel17**
These are the sections of the app I'm most familiar with.

I'm busier nowadays and am having trouble keeping up with notifications when watching the whole repo, which means I might be missing pings or changes that I *should* be paying attention to. So, I'm going to switch my notifications back to "Participating and mentions". But I still want to get notifications when someone touches these files.

### CODE REVIEW

**Comment by FloEdelmann** [comment]
@mnalis I also noticed that today, so I asked @rugk already in https://github.com/streetcomplete/StreetComplete/pull/3764#issuecomment-1066685956 :wink:

**Comment by rugk** [comment]
Ah it only works when you actually have write access, so well… okay, feel free to remove me there.

**Comment by westnordost** [comment]
Uhm well, you **do** have read access. So, I consider this a bug / missing feature in github, so let's keep you in the file even if it doesn't work.

**Comment by smichel17** [comment]
It makes some sense— it's the code**owners** file, not code*watchers*, and it's hard to argue that you own something if you're not allowed to modify it (though it seems many tech companies would like to deny that.. *glances at locked-bootloader phone :rage:*).

Actually, I guess the issue might be notification spam. If you don't have write access, you can't remove your name if you don't want the notifications.

**Comment by westnordost** [comment]
Well, but you are certainly not the codeowner of the `streetcomplete.map` package, so I very much interpret this as _codewatchers_.

**Pull request merged**
