### PR TITLE
update screenshots used in the readme file

### PR DESCRIPTION
**Pull request by RubenKelevra**
Due to the switch of renderers in version 59.0 (Alpha 1) I think it's time to update the screenshots.

I tried to reproduce the original screenshots, used in the readme, as close as possible. But some quests and the notes were no longer available, so I replaced them with similar content.

Hope that's fine.

### CODE REVIEW

**Comment by westnordost** [comment]
see https://github.com/streetcomplete/StreetComplete/discussions/5812#discussioncomment-10411118

**Comment by RubenKelevra** [comment]
Yes of course. The default is laughably large for some reason.

**Comment by westnordost** [comment]
Or maybe you just have big eyes

**Comment by westnordost** [comment]
...or small eyes? 🤔

**Comment by RubenKelevra** [comment]
> Or maybe you just have big eyes

I'm the Big Bad Wolf ;D

**Pull request closed without merging**
