### PR TITLE
put charging station quests in one package

### PR DESCRIPTION
**Pull request by matkoniecz**
I want to do similar merges in other cases - folder listing of quests is getting quite long

### CODE REVIEW

**Comment by westnordost** [comment]
I don't know, what exactly is the advantage of this? The reason why there are these packages is so that the quest UI and quest logic are in the same place. Whether they are related through the properties they edit is not really relevant from a code perspective - i.e. they have no code interdependencies, have they?

**Comment by matkoniecz** [comment]
Primarily? Finding correct quest in this window would be easier.

screen

Though maybe I should navigate less by mouse and more by keyboard and/or write code outside Android Studio?

**Comment by westnordost** [comment]
Have you used Ctrl+N before? That's how you find individual quests easily.

**Comment by matkoniecz** [comment]
I guess that I should try that first

**Comment by westnordost** [comment]
And Ctrl+Shift+N for "any file with that name"

**Pull request closed without merging**
