### PR TITLE
Remove "bridge" from height limit texts, as pipelines and roofs will now appear as well

### PR DESCRIPTION
**Pull request by RubenKelevra**
Additional fix for #5912

### CODE REVIEW

**Comment by westnordost** [comment]
What? No, we already have a text for that, `quest_maxheight_sign_title`

**Comment by westnordost** [comment]
Ah, but I see the issue... hmm...

**Comment by westnordost** [comment]
It is now impossible to tell apart the situation "below a bridge", "below an overhead pipeline" and "below a building roof". So, I guess, the string should be removed for all. I hope this does not lead to confusion.

**Comment by RubenKelevra** [comment]
I don't think so. I mean if you're standing on top of a bridge and it marks the road crossing blow on the map, I doubt anyone would think "there's no sign here on the bridge, let's put this in". :)

**Comment by mnalis** [comment]
Although, I seem to recall discussions there was confusion even earlier, if the section of the road going under the bridge was long (i.e. the quest would pop up a kilometer before the bridge is even visible). I do not recall if a proper fix was devised; if not, making the text even more generic is likely to be even more confusing.

**Comment by westnordost** [comment]
But there is no alternative, or is there?

**Comment by mnalis** [comment]
> But there is no alternative, or is there?

For the original confusion, or the new one?

- for the original confusion (e.g. https://github.com/streetcomplete/StreetComplete/issues/4588), perhaps quest might be skipped if road segment going under the bridge is too long (maybe `> 1km` or something like that?) I don't know how complicated that would be, but it would reduce confusion (at the expense at not asking the quest in some situations)

- for this newly increased confusion, `getTitle()` can be changed programmatically, like e.g. in `air_pump/AddBicyclePump.kt`. That would require separate translations, though, but would reduce the confusion to (much smaller) original levels.

Also quest description (the one behind info button) could be improved to at least mention all the things that this quest may apply to, and the fact that they may be somewhat far away.

**Comment by RubenKelevra** [comment]
> Although, I seem to recall discussions there was confusion even earlier, if the section of the road going under the bridge was long (i.e. the quest would pop up a kilometer before the bridge is even visible). I do not recall if a proper fix was devised; if not, making the text even more generic is likely to be even more confusing.

This highlights the main training issue I currently see in SC. Many beginners tend to walk to a quest marker, click on it, and then ignore the map, because the answer field opened up and draws their attention. Leading to them applying the information for the current situation the specific spot to the entire way. For longer ways, especially those over 200 meters, users who behave correctly still have to rely on memory, which becomes unreliable over such distances, leading to incorrect tagging.

My suggestion to address this could be implementing a prompt when a way exceeds 200 meters. The prompt would encourage them to split the way into smaller, manageable sections and only tag what they can visually confirm at the time of answering. This would prevent users from having to rely on memory, which often results in inaccuracies. By guiding users to divide the way into sections, they can tag each part with the appropriate information and avoid applying localized data across an entire way.

This approach could significantly improve data accuracy and reduce the common mistakes I’ve observed in OSM contributions from StreetComplete users.

The only draw back I see is that ways may be split up unnecessarily in some circumstances, but to be fair, that's better than having wrong information in the database IMHO.

**Comment by RubenKelevra** [comment]
@westnordost thinking about it... It should be pretty easy to implement:

- If the way of a quest is longer than 200m, show a popup:

"The way on the map is pretty long! Please mark on it how far you can see from your current location" (with an "OK" button on the right and a "skip" button on the left) 

- Then transition to the regular "split way" function, but limit it to two cuts and require at least one cut.
- Afterwards reopen the quest for the middle section (on two cuts) or the small section (on one cut)

**Comment by westnordost** [comment]
Nobody reads prompts of the "are you sure" type, though.

**Comment by westnordost** [comment]
> for this newly increased confusion, getTitle() can be changed programmatically, like e.g. in air_pump/AddBicyclePump.kt. That would require separate translations, though, but would reduce the confusion to (much smaller) original levels.

No, it can't, because passed into `getTitle` are the tags of the object for which the quest is created. In this case, the road below the roof or bridge. There is nothing tagged on that section of road that would help in deciding whether that section of road is below a bridge, roof or overhead pipeline.

**Comment by mnalis** [comment]
> There is nothing tagged on that section of road that would help in deciding whether that section of road is below a bridge, roof or overhead pipeline.

Ah, that is unfortunate. Splitting the quest into three separate similar-looking quests would work instead I guess, but seems quite inelegant solution :thinking: 

> If the way of a quest is longer than 200m, show a popup

While cutting would in the end reduce the confusion, I'm afraid that cure might be quite _worse_ then the original illness  **_if applied generally_** (spamminess, significant work multiplication, etc. See related https://github.com/streetcomplete/StreetComplete/issues/5101 for some of the issues). 

However, applied just for the (rather rare) `maxheight` quest on too long ways there, such force-splitting might work (especially if they're instructed to just cut on the sides of the bridge)

**Comment by goldfndr** [comment]
Instead of getTitle, could getLevelLabel (or a caller or other function) be overridden with another (or optional) parameter that would pass the overhead object and supplement the italicized description?

**Comment by mnalis** [comment]
I'd add _", overhead pipes"_ before _"etc..."_, but yes; it should help  (provided people read it and are not overly confused)

**Pull request closed without merging**
