### PR TITLE
Add bus stop timetable quest

### LINKED ISSUE #1974: Quest: Is there an information display at this bus/tram stop?
### General
Affected tag(s) to be modified/added: [passenger_information_display](https://wiki.openstreetmap.org/wiki/Key:passenger_information_display)
Question asked: **Is there an information display at this bus stop?** or **Is there an information display at this tram stop?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** 
`public_transport = "platform" and !passenger_information_display`

**Proposed GUI:**
Simple Yes/No

### Related

Briefly mentioned in https://github.com/westnordost/StreetComplete/issues/1079#issuecomment-417069812.

### LINKED ISSUE #2263: Departures Board at Public Transport Locations
### General
Affected tag(s) to be modified/added: [departures_board](https://wiki.openstreetmap.org/wiki/Key:departures_board)
Question asked: **Is there a departures board at this platform/station?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
   * De facto status
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** 
Selected for elements with `public_transport=platform` or `public_transport=station`, and the older tags `highway=bus_stop` or `railway=platform`. Where `departures_board`  nor `passenger_information_display` does not already exist as a tag.

**Proposed GUI:**
Picture selection to choose between the options (`timetable`/`realtime`/`delay`/`no`). Similar in structure to the path surface quest. `Other Answers` button which contains the choices for "cannot say" and "yes". Each answer directly corresponds to the tag information.

<table>
    <tbody>
        <tr>
            <td>Timetable </td>
            <td>Realtime </td>
            <td>Delay</td>
            <td>No</td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td>
</td>
            <td></td>
        </tr>
        <tr>
            <td colspan="4">Other Answers</td>
        </tr>
    </tbody>
</table>

On selecting `Other Answers`: 
| Yes | Cannot Say |
| --- | --- |

Selecting "yes" provides a prompt for "If possible, please be more specific"

**Other Issues**
[passenger_information_display](https://wiki.openstreetmap.org/wiki/Key:passenger_information_display) is similar. `passenger_information_display=yes` covers the case of `departures_board=realtime`. The `departures_board` tag is more general since it can also map other sorts of boards.

### PR DESCRIPTION
**Pull request by TurnrDev**
Adds `departures_board` and `passenger_information_display` tags for bus stops based on [the wiki](https://wiki.openstreetmap.org/wiki/Key:departures_board)

~~Built @ 72690b9bc849a7fa446ff546412e3141ac8a56cd: works with a minor bug~~
Built @ 1eddc2078e7f5db7a9d374866a29871710f93789: works, filter bug fixed, added comments. 

Still needs:
- [x] fix filter
- [ ] quest icon
- [ ] consistent images/drawings for selections
- [ ] to be placed in an achievement

Fixes #2263
Fixes #1974

### CODE REVIEW

**Comment by TurnrDev** [comment]
@westnordost If you think this quest is a good idea, could you create an icon for it? :) 

I plan to set out and capture my own images of each example so the ratios are the same.

**Comment by FloEdelmann** [comment]
See #2263 and #1974.

**Comment by TurnrDev** [comment]
In response to https://github.com/streetcomplete/StreetComplete/issues/1974#issuecomment-686969766, I will post on the tagging mailing list 😇

**Comment by RubenKelevra** [comment]
Hey @TurnrDev, thanks for the PR!

`departures_board=realtime` (and the other values) is fine for me, while `passenger_information_display` is not. An information display for passengers could basically mean everything related to transportation and not necessarily refers to an departures board.

For example there are displays on some Chinese Airports where you can get more info about yourself flight. But the display reacts to you based on face recognition and isn't showing general departure information.

So something like `passenger_information_display=departures_board` would make sense IMHO. Since most bus stops have both here: paper time tables as well as digital departure boards covering the next 4-5 busses. 

But that's just my opinion on those tags.

**Comment by westnordost** [comment]
While both tags exist and none is favoured/deprecated, this PR cannot be merged.

**Comment by TurnrDev** [comment]
Yeah from what I'm understanding is that this is basically blocked until the community comes to a consensus

**Comment by TurnrDev** [comment]
Not even sure if this is super useful

**Comment by westnordost** [comment]
TBH I don't really like to keep around PRs that are obviously blocked by something external. I'll close this, and you can reopen this if it is not blocked anymore.

**Pull request closed without merging**
