### PR TITLE
Update images on Bridge Structure quest

### PR DESCRIPTION
**Pull request by TurnrDev**
Fixes #2854

New images, as shown in https://github.com/streetcomplete/StreetComplete/pull/2854#issuecomment-835999598

### CODE REVIEW

**Comment by westnordost** [comment]
Looks really nice so far!

I have a few comments on those:
- Android caches a rasterized version of the Android drawables (as far as I know) in the size specified that the Android drawable has. Also, as Androids below 5.0 do not support vector graphics, the Android build tools converts those graphics to raster and includes them in the APK. In the size specified that the Android drawable has. To cut a long story short: Please specify the actual values for `android:width` and `android:height` in the `<vector>`-graphics rather than 2000/1000.
- Since the graphics fill one horizontal line, it would make more sense to me if their aspect ratio was about 3:1, precisely, 320x96
- It would be great if the strokes used were at least 1dp (on that resolution) broad, better yet 2 or 4 dp. I know, this is a shortcoming of the roof shape pictures too, the strokes should be thicker
- The humpback bridge looks very odd. I know it is very much inspired by that photo. But isn't there a less extreme example of a humpback bridge? F.e. this is a humpback bridge too: https://www.alamy.com/stock-photo-england-devon-dartmoor-stone-bridge-at-two-bridges-52246852.html Generally, according to the wikipedia, a humpback is basically an arch bridge but where the central part of the bridge is also the highest, see https://en.wikipedia.org/wiki/Humpback_bridge

**Comment by westnordost** [comment]
Also, you should put yourself as the author of the files in the authors.txt (and remove the copyright info for the old photos)

**Comment by TurnrDev** [comment]
Of course, I'm moving house today so all my PRs are on hold until I'm all set up again 😊

I wanna match the gradient on the bridge graphics to the same as roof too 😄

**Comment by westnordost** [comment]
happy 🚚📦

**Comment by westnordost** [comment]
You are almost done here. Would be great to get this into the next release

**Comment by TurnrDev** [comment]
I totally forgot omg! I'll get on this one 😊

**Comment by matkoniecz** [comment]
@TurnrDev ping?

**Comment by TurnrDev** [comment]
> @TurnrDev ping?

Arghhhh, I lost access to Illustrator! I got today off, I'll try to tackle this one via a FOSS vector editor

**Comment by westnordost** [comment]
Inkscape?

Am 25. August 2021 08:51:23 MESZ schrieb Jay Turner ***@***.***>:
>> @TurnrDev ping?
>
>Arghhhh, I lost access to Illustrator! I got today off, I'll try to
>tackle this one via a FOSS vector editor
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/pull/2867#issuecomment-905232184

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
Alright, I reviewed and edited all the bridges, redid a few.

Say, @TurnrDev , under which license do you want to put your graphics? CC-BY-SA, CC-BY or CC-0?

**Comment by TurnrDev** [comment]
Thank you, I truly appreciate that. It was stressing me out, graphics really aren't my forté. CC0 is fine by me ☺️

**Comment by westnordost** [comment]
Now it looks like this:

image

(Interesting, the colors are different than in your screenshot. But I didn't change them 🤷 )

**Comment by TurnrDev** [comment]
> (Interesting, the colors are different than in your screenshot. But I didn't change them 🤷 )

It might be your phone profile :) Night reading mode etc

**Comment by westnordost** [comment]
Thank you for your work on this!

**Comment by mnalis** [comment]
It looks very nice @westnordost (and thanks @TurnrDev too!)

Maybe the hanging bridge could have its base (the surface one walks on) a little thinner to indicate it is not a heavy piece of concrete or steel (like it is in other bridges)?

**Pull request merged**
