### PR TITLE
Reuse

### PR DESCRIPTION
**Pull request by NSfsfe**
Hello,

By way of introduction, I am Niharika with the Free Software Foundation Europe, a consortium member of the NGI0 Initiative, of which you have signed xqerl up for participation and funding. Part of what is offered with your involvement with NGI0 is help from us with your project on your copyright and license management.

After a quick check on your repository, I would like to propose some updates regarding copyright and licensing information in your files. Our REUSE specifications (https://reuse.software/) intend to make licensing easier with best practices to display legal information through comment headers on source files that can be easily human and machine readable. The REUSE tool makes the process of applying licenses to files and compliance checking much easier.

Instructions on how to install the REUSE tool can be found here: https://reuse.readthedocs.io/en/stable/readme.html#install

You can also check out this screencast for more instructions on how to use the REUSE tool: https://download.fsfe.org/videos/reuse/screencasts/reuse-tool.gif

The changes in this pull request have also been made for you to understand the basic ideas behind REUSE, and how adopting the REUSE practices would look like within your repository.
REUSE Features:

• SPDX copyright and license comment headers for relevant files.

• LICENSES directory with licenses used in the repository

• Associating copyright/licensing information through a DEP5 file in large directories.
Files Missing Copyright and Licensing Information

The idea behind REUSE is that every single file in your repository should have a header that includes this information.

To serve as an example, I added the SPDX headers with copyright and license information to one of the directories (namely /res folder). This should give you an idea of how comment headers should look like in a REUSE compliant repository.

Please also check if the personal information in these headers are correct and consistent to your knowledge. In the event that there are more copyright holders, please include them in these comment headers.
LICENSES Directory in the Root of the Project Repository

The LICENSES Folder should contain the license text of every license applicable in your repository. I included in this directory the file that contained the GPL-3.0-only license text.

Adding a license file for every image file:
I added the GPL.v.03 only license to all of the image files located in the dep5 file in the .reuse folder at the root. However, you can license other image files under licenses as well and include the license in the LICENSES directory.

I hope that you find this useful and please feel free to contact me directly at [[niharika@fsfe.org](mailto:niharika@fsfe.org)] if you have any questions.

Best,

Niharika

(Free Software Foundation Europe)

### CODE REVIEW

**Comment by matkoniecz** [comment]
Independently from whether this specific formatting is useful: why I am set as author of several files where I am not author at all?

Or is it not supposed to be only demonstration of formatting?

Now that there is already got example https://github.com/streetcomplete/StreetComplete/blob/master/res/graphics/authors.txt tracking authors and licenses

**Comment by westnordost** [comment]
@matkoniecz Since you have been our licensing guy, would you take care of this?

I propose you have a look at where our current licensing info is lacking, how or if this tool can help us and rehash this into a new ticket or pull request (if nothing needs discussion + you also want to take care of the implementation).

Since it was mentioned that ideally, every single source code file should have the license attached to the top of the file: I'd very much like to not do that and I do not really care about compliance in this regard, only if it has serious legal repercussions.

From my point of view, there should be a central and standard place (`LICENSE.md`? `README.md`?) from which all the license information is available or linked and that should be enough, both for being easily accessible and for legal/licensing reasons.

**Comment by matkoniecz** [comment]
@NSfsfe what is the role of adding this headers? I am also not a fan of it for ergonomic/practical reasons.

Does it have serious legal impact? Or any legal impact at all?

**Comment by westnordost** [comment]
From what I remember, the official site (gnu.org or something) actually recommends it, and I think the reason was so that there is not any doubt about the origin (that it is a breach of license should this file be found somewhere else). But with this argumentation, one could also say that the license should be attached to each function or something.

For the use case that someone takes the code in the file, be it just a part of it or all of it, he then needs to attribute it correctly somewhere in his repo. I.e. he can not simply copy the whole file, he'll either have to add the GPL header then or mention this somewhere in his LICENSE file or whatever. So one might say it is slightly more convenient to share if the GPL header is there. But really, not a strong argument IMO.

**Comment by NSfsfe** [comment]
Hi,

The headers ensure a complete downstream compliance with copyright should anyone use any file from your repository. Instead of attributing the correct license information somewhere in their directory, having a header makes the license compliance much simpler not only for the direct user of repository, but for the entire downstream use of the licensed files.

The REUSE helper tool also identifies any missing license information in your repository and since it is automated, it is pretty simple and easy to use to add any such missing copyright and license information to multiple file types without worrying about and manually entering the correct comment header syntax.

**Comment by westnordost** [comment]
Closing this as the PR itself has just been an demonstration of the capabilities of the tool and the information has been acknowledged.

**Pull request closed without merging**
