### PR TITLE
Fix typo in changeset message

### PR DESCRIPTION
**Pull request by eginhard**

### CODE REVIEW

**Comment by westnordost** [comment]
Oh, haha, @matkoniecz strikes again ;-) Didn't notice it, thanks!

(He implemented this quest and he is not a native speaker)

**Comment by smichel17** [comment]
Being a native speaker is no protection… I misspell receive (as recieve) nearly every time I type it :P

**Comment by westnordost** [comment]
by the way, "ei" is pronounced like "aye" in German

**Comment by matkoniecz** [comment]
aarghhh.

whatever vs whether is my most common mistake. In addition to missing "a"/"an"/"the" - but this is explainable as Polish is without such grammatical construct. But "whatever" replacing "whether" is some weird habit.

Thanks for catching it!

**Pull request merged**
