### PR TITLE
make 'no bicycle infrastructure here' more visible, first part of #2285

### PR DESCRIPTION
**Pull request by matkoniecz**
I want to add also hint, but it is also useful and would be nice to refer to some clearly visible symbol

my main worry here is risk that people will interpret it as 'no cycling allowed' but hopefully it is unlikely

### CODE REVIEW

**Comment by matkoniecz** [comment]
screen18

**Comment by matkoniecz** [comment]
Now that I look at it - maybe also move "none" to the first position?

**Comment by matkoniecz** [comment]
Tested in country with left-hand traffic, in night mode, in night mode in country with left-hand traffic.

**Comment by theraser** [comment]
Thanks, nice! Would it be possible to use exactly the same icon as for sidewalks for a more similar feeling/look? It seems that the ❌ in your version is more in the middle of the icon that at the sidewalks one. Moving it more to the left/right maybe would avoid your concerns:

> my main worry here is risk that people will interpret it as 'no cycling allowed' but hopefully it is unlikely

**Comment by matkoniecz** [comment]
Yes, it is moved to a side.

This was deliberate to avoid interpreting it as "no cycleway along cariageway" but rather as "no cycleway infrastructure at all".

I though also about changing it to another symbol like a sad face, or empty set symbol but I was not convinced that it would be more clear.

**Comment by westnordost** [comment]
The X would be visible also in the preview, wouldn't it? That's not consistent with the sidewalk quest

**Comment by matkoniecz** [comment]
> The X would be visible also in the preview, wouldn't it?

Yes.

> That's not consistent with the sidewalk quest

So bikeway quest should be modified to allow displaying different graphic in selection menu and different in a lane view?

**Comment by matkoniecz** [comment]
Personally I have no trouble with the difference but having it consistent is also fine.

**Comment by westnordost** [comment]
I'd say so, yes

**Comment by matkoniecz** [comment]
I see two options: 

(1) special casing this single situation in showCyclewaySelectionDialog

(2) duplicate entire `getLeftHandTrafficIconResId` `getRightHandTrafficIconResId`

Version (1) seemed nicer despite hard-coding, but it is happening in the different file. I will go with (2).

**Comment by westnordost** [comment]
(3) special-casing this situation in 
```kotlin
fun Cycleway.getIconResId(isLeftHandTraffic: Boolean): Int =
    if (this == NONE) R.drawable.ic_cycleway_none_with_X
    else getPuzzleIconResId()

fun Cycleway.getPuzzleIconResId(isLeftHandTraffic: Boolean): Int =
    if (isLeftHandTraffic) getLeftHandTrafficIconResId() else getRightHandTrafficIconResId()
```

and use `getPuzzleIconResId` in `AddCyclewayForm`

**Comment by matkoniecz** [comment]
I ended special casing in a bit different location, hopefully it is also OK.

**Review by westnordost — APPROVED** [review]

**Pull request merged**
