### PR TITLE
Don't ask path smoothness for highway=pedestrian

### LINKED ISSUE #4180: Path and Road smoothness both ask for highway=pedestrian
Currently both smoothness quests ask smoothness for highway=pedestrian.
This is not horrible, but confusing when hiding a smoothness quest. I think only one of the quests should apply.

I don't have any clear preference which quest shoud apply. RoadSmoothness makes a bit more sense, as then it's in line with surface quests.

### PR DESCRIPTION
**Pull request by Helium314**
fixes #4180

Smoothness for highway=pedestrian is already asked in the road smoothness quest.
According to the (now removed) comment, I added pedestrian to path smoothness with the idea of having the smoothness description text dependent on whether it's a path or a road. But anyway, looks like this wasn't implemented in the end.

### CODE REVIEW

**Review by matkoniecz — APPROVED** [review]
looks good

have you tested it?

**Comment by Helium314** [comment]
No, I did not.
Do you think it's necessary?

**Comment by westnordost** [comment]
It's always better, one may never know what one overlooked.

**Comment by matkoniecz** [comment]
I have run into compilation failures and severe bugs before that I have not spotted or expected.

**Comment by Helium314** [comment]
Tested, and now there is no path smoothness quest asked for highway=pedestrian (only road smoothness)

**Pull request merged**
