### PR TITLE
Re-enable R8 full mode

### LINKED ISSUE #5360: R8 error when running Android tests
Running the Android test I'm getting errors about R8.

```
Missing class com.google.errorprone.annotations.MustBeClosed (referenced from: androidx.test.platform.tracing.Tracer$Span androidx.test.platform.tracing.Tracer$Span.beginChildSpan(java.lang.String) and 2 other contexts)
Missing class com.sun.jna.FunctionMapper (referenced from: net.bytebuddy.dynamic.loading.ClassInjector$UsingJna$Dispatcher$Windows32BitFunctionMapper)
Missing class com.sun.jna.JNIEnv (referenced from: java.lang.Class net.bytebuddy.dynamic.loading.ClassInjector$UsingJna$Dispatcher$Enabled.defineClass(java.lang.ClassLoader, java.lang.String, byte[], java.security.ProtectionDomain) and 1 other context)
Missing class com.sun.jna.LastErrorException (referenced from: int net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaPosixSocket$PosixLibrary.close(int) and 19 other contexts)
Missing class com.sun.jna.Library (referenced from: net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaPosixSocket$Factory$MacLibrary and 4 other contexts)
Missing class com.sun.jna.Memory (referenced from: net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$Factory net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaPosixSocket$Factory.withDefaultTemporaryFolder(int, long, java.util.concurrent.TimeUnit) and 1 other context)
Missing class com.sun.jna.Native (referenced from: void net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaPosixSocket$Factory.<init>(java.lang.String, int, long, java.util.concurrent.TimeUnit) and 14 other contexts)
Missing class com.sun.jna.NativeLibrary (referenced from: java.lang.String net.bytebuddy.dynamic.loading.ClassInjector$UsingJna$Dispatcher$Windows32BitFunctionMapper.getFunctionName(com.sun.jna.NativeLibrary, java.lang.reflect.Method))
Missing class com.sun.jna.Platform (referenced from: net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$Factory net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaPosixSocket$Factory.withDefaultTemporaryFolder(int, long, java.util.concurrent.TimeUnit) and 4 other contexts)
Missing class com.sun.jna.Pointer (referenced from: com.sun.jna.Pointer net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaSolarisDoor$SolarisLibrary$DoorArgument.dataPointer and 11 other contexts)
Missing class com.sun.jna.Structure (referenced from: void net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaPosixSocket$PosixLibrary$SocketAddress.<init>() and 7 other contexts)
Missing class com.sun.jna.platform.win32.Advapi32 (referenced from: net.bytebuddy.agent.VirtualMachine$ForOpenJ9$Dispatcher$ForJnaWindowsEnvironment$AttachmentHandle net.bytebuddy.agent.VirtualMachine$ForOpenJ9$Dispatcher$ForJnaWindowsEnvironment.openSemaphore(java.io.File, java.lang.String, boolean))
Missing class com.sun.jna.platform.win32.Kernel32 (referenced from: net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaWindowsNamedPipe$Factory.connect(java.lang.String) and 11 other contexts)
Missing class com.sun.jna.platform.win32.Win32Exception (referenced from: net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaWindowsNamedPipe$Factory.connect(java.lang.String) and 10 other contexts)
Missing class com.sun.jna.platform.win32.WinBase$OVERLAPPED (referenced from: int net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaWindowsNamedPipe$NamedPipeResponse.read(byte[]) and 1 other context)
Missing class com.sun.jna.platform.win32.WinBase$SECURITY_ATTRIBUTES (referenced from: com.sun.jna.platform.win32.WinNT$HANDLE net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaWindowsNamedPipe$WindowsLibrary.CreateRemoteThread(com.sun.jna.platform.win32.WinNT$HANDLE, com.sun.jna.platform.win32.WinBase$SECURITY_ATTRIBUTES, int, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.platform.win32.WinDef$DWORD, com.sun.jna.Pointer) and 2 other contexts)
Missing class com.sun.jna.platform.win32.WinDef$DWORD (referenced from: com.sun.jna.platform.win32.WinDef$DWORD net.bytebuddy.agent.VirtualMachine$ForOpenJ9$Dispatcher$ForJnaWindowsEnvironment$WindowsLibrary$SecurityAttributes.length and 3 other contexts)
Missing class com.sun.jna.platform.win32.WinDef$LPVOID (referenced from: com.sun.jna.platform.win32.WinDef$LPVOID net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaWindowsNamedPipe.code and 6 other contexts)
Missing class com.sun.jna.platform.win32.WinNT$ACL (referenced from: net.bytebuddy.agent.VirtualMachine$ForOpenJ9$Dispatcher$ForJnaWindowsEnvironment$AttachmentHandle net.bytebuddy.agent.VirtualMachine$ForOpenJ9$Dispatcher$ForJnaWindowsEnvironment.openSemaphore(java.io.File, java.lang.String, boolean))
Missing class com.sun.jna.platform.win32.WinNT$HANDLE (referenced from: com.sun.jna.platform.win32.WinNT$HANDLE net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaWindowsNamedPipe$NamedPipeResponse.pipe and 28 other contexts)
Missing class com.sun.jna.platform.win32.WinNT$SECURITY_DESCRIPTOR (referenced from: net.bytebuddy.agent.VirtualMachine$ForOpenJ9$Dispatcher$ForJnaWindowsEnvironment$AttachmentHandle net.bytebuddy.agent.VirtualMachine$ForOpenJ9$Dispatcher$ForJnaWindowsEnvironment.openSemaphore(java.io.File, java.lang.String, boolean))
Missing class com.sun.jna.ptr.IntByReference (referenced from: int net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaWindowsNamedPipe$NamedPipeResponse.read(byte[]) and 3 other contexts)
Missing class com.sun.jna.win32.StdCallLibrary (referenced from: net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaWindowsNamedPipe$WindowsAttachLibrary and 2 other contexts)
Missing class com.sun.jna.win32.W32APIOptions (referenced from: void net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaWindowsNamedPipe$Factory.<init>())
Missing class edu.umd.cs.findbugs.annotations.SuppressFBWarnings (referenced from: short net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaPosixSocket$PosixLibrary$SocketAddress.family and 256 other contexts)
Missing class java.lang.instrument.ClassDefinition (referenced from: void net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector$ForRedefinition.doApply(java.lang.instrument.Instrumentation, java.util.List) and 4 other contexts)
Missing class java.lang.instrument.ClassFileTransformer (referenced from: java.lang.instrument.ClassFileTransformer net.bytebuddy.dynamic.loading.ClassFilePostProcessor$ForClassFileTransformer.classFileTransformer and 32 other contexts)
Missing class java.lang.instrument.IllegalClassFormatException (referenced from: byte[] net.bytebuddy.agent.builder.AgentBuilder$Default$WarmupStrategy$Enabled$Dispatcher.transform(java.lang.instrument.ClassFileTransformer, java.lang.Object, java.lang.ClassLoader, java.lang.String, java.lang.Class, java.security.ProtectionDomain, byte[]) and 1 other context)
Missing class java.lang.instrument.Instrumentation (referenced from: java.lang.instrument.Instrumentation net.bytebuddy.agent.ByteBuddyAgent.UNAVAILABLE and 197 other contexts)
Missing class java.lang.instrument.UnmodifiableClassException (referenced from: void net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector$ForRedefinition.doApply(java.lang.instrument.Instrumentation, java.util.List) and 14 other contexts)
Missing class java.lang.management.ManagementFactory (referenced from: java.lang.String net.bytebuddy.agent.ByteBuddyAgent$ProcessProvider$ForCurrentVm$ForLegacyVm.resolve() and 1 other context)
Missing class java.lang.management.RuntimeMXBean (referenced from: java.lang.String net.bytebuddy.agent.ByteBuddyAgent$ProcessProvider$ForCurrentVm$ForLegacyVm.resolve())
Missing class java.lang.management.ThreadInfo (referenced from: java.lang.String org.assertj.core.internal.Failures.threadDumpDescription())
Missing class java.lang.management.ThreadMXBean (referenced from: java.lang.String org.assertj.core.internal.Failures.threadDumpDescription())
Missing class org.junit.jupiter.api.TestInstance$Lifecycle (referenced from: boolean org.assertj.core.api.junit.jupiter.SoftAssertionsExtension.isPerClass(org.junit.jupiter.api.extension.ExtensionContext) and 3 other contexts)
Missing class org.junit.jupiter.api.extension.AfterEachCallback (referenced from: org.assertj.core.api.JUnitJupiterBDDSoftAssertions and 1 other context)
Missing class org.junit.jupiter.api.extension.AfterTestExecutionCallback (referenced from: org.assertj.core.api.junit.jupiter.SoftAssertionsExtension and 1 other context)
Missing class org.junit.jupiter.api.extension.BeforeEachCallback (referenced from: org.assertj.core.api.junit.jupiter.SoftAssertionsExtension)
Missing class org.junit.jupiter.api.extension.ExtensionConfigurationException (referenced from: java.lang.Class org.assertj.core.api.junit.jupiter.SoftAssertionsExtension.asSoftAssertionsProviderClass(java.lang.reflect.Field, java.lang.Class) and 4 other contexts)
Missing class org.junit.jupiter.api.extension.ExtensionContext$Namespace (referenced from: org.junit.jupiter.api.extension.ExtensionContext$Namespace org.assertj.core.api.junit.jupiter.SoftAssertionsExtension.SOFT_ASSERTIONS_EXTENSION_NAMESPACE and 5 other contexts)
Missing class org.junit.jupiter.api.extension.ExtensionContext$Store (referenced from: org.assertj.core.api.AssertionErrorCollector org.assertj.core.api.junit.jupiter.SoftAssertionsExtension.getAssertionErrorCollector(org.junit.jupiter.api.extension.ExtensionContext) and 8 other contexts)
Missing class org.junit.jupiter.api.extension.ExtensionContext (referenced from: void org.assertj.core.api.JUnitJupiterBDDSoftAssertions.afterEach(org.junit.jupiter.api.extension.ExtensionContext) and 24 other contexts)
Missing class org.junit.jupiter.api.extension.ParameterContext (referenced from: java.lang.Object org.assertj.core.api.junit.jupiter.SoftAssertionsExtension.resolveParameter(org.junit.jupiter.api.extension.ParameterContext, org.junit.jupiter.api.extension.ExtensionContext) and 1 other context)
Missing class org.junit.jupiter.api.extension.ParameterResolutionException (referenced from: boolean org.assertj.core.api.junit.jupiter.SoftAssertionsExtension.supportsParameter(org.junit.jupiter.api.extension.ParameterContext, org.junit.jupiter.api.extension.ExtensionContext))
Missing class org.junit.jupiter.api.extension.ParameterResolver (referenced from: org.assertj.core.api.junit.jupiter.SoftAssertionsExtension)
Missing class org.junit.jupiter.api.extension.TestInstancePostProcessor (referenced from: org.assertj.core.api.junit.jupiter.SoftAssertionsExtension and 1 other context)
Missing class org.junit.jupiter.api.parallel.Execution (referenced from: boolean org.assertj.core.api.junit.jupiter.SoftAssertionsExtension.isAnnotatedConcurrent(org.junit.jupiter.api.extension.ExtensionContext))
Missing class org.junit.jupiter.api.parallel.ExecutionMode (referenced from: boolean org.assertj.core.api.junit.jupiter.SoftAssertionsExtension.isAnnotatedConcurrent(org.junit.jupiter.api.extension.ExtensionContext) and 1 other context)
Missing class org.junit.platform.commons.annotation.Testable (referenced from: boolean org.assertj.core.api.junit.jupiter.SoftAssertionsExtension.supportsParameter(org.junit.jupiter.api.extension.ParameterContext, org.junit.jupiter.api.extension.ExtensionContext))
Missing class org.junit.platform.commons.support.AnnotationSupport (referenced from: boolean org.assertj.core.api.junit.jupiter.SoftAssertionsExtension.isAnnotatedConcurrent(org.junit.jupiter.api.extension.ExtensionContext) and 2 other contexts)
Missing class org.junit.platform.commons.support.HierarchyTraversalMode (referenced from: void org.assertj.core.api.junit.jupiter.SoftAssertionsExtension.postProcessTestInstance(java.lang.Object, org.junit.jupiter.api.extension.ExtensionContext) and 1 other context)
Missing class org.junit.platform.commons.support.ReflectionSupport (referenced from: org.assertj.core.api.SoftAssertionsProvider org.assertj.core.api.junit.jupiter.SoftAssertionsExtension.instantiateProvider(org.junit.jupiter.api.extension.ExtensionContext, java.lang.Class) and 3 other contexts)
Missing class org.mockito.internal.creation.bytebuddy.inject.MockMethodDispatcher (referenced from: void org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.<init>(java.lang.instrument.Instrumentation, org.mockito.internal.util.concurrent.WeakConcurrentMap, org.mockito.internal.util.concurrent.DetachedThreadLocal, java.util.function.Predicate, org.mockito.internal.creation.bytebuddy.ConstructionCallback) and 9 other contexts)
Missing class org.opentest4j.AssertionFailedError (referenced from: void org.mockito.exceptions.verification.opentest4j.ArgumentsAreDifferent.<init>(java.lang.String, java.lang.String, java.lang.String) and 2 other contexts)
Missing class org.opentest4j.MultipleFailuresError (referenced from: void org.assertj.core.error.AssertJMultipleFailuresError.<init>(java.lang.String, java.util.List) and 2 other contexts)
Missing class org.w3c.dom.bootstrap.DOMImplementationRegistry (referenced from: java.lang.String org.assertj.core.util.xml.XmlStringPrettyFormatter.prettyFormat(org.w3c.dom.Document, boolean))
```

@riQQ  noted that setting `android.enableR8.fullMode=false` to the build.gradle solves this (by making R8 less aggressive). This however would also change R8's behavior for app builds.

### PR DESCRIPTION
**Pull request by riQQ**
Fix #5360

### CODE REVIEW

**Comment by westnordost** [comment]
But doesn't dontwarn mean that it doesn't warn about it but it could still be that these are required?

**Comment by westnordost** [comment]
Or, anyway, did you test that the tests and androidTests run through correctly?

**Comment by riQQ** [comment]
I ran *androidTest* and the same tests failed as before my test.

As far as I unstand it, this doesn't affect unit tests as they don't use the instrumentation apk. See also https://stackoverflow.com/questions/31988579/android-gradle-testproguardfile-what-is-its-purpose-relating-to-unit-tests.

**Comment by westnordost** [comment]
Oh, tests are failing on androidTest? Gotta check...

**Comment by westnordost** [comment]
Hmm, no idea about these errors. Not the fault of this repo though, I think.

So, thanks!

**Pull request merged**
