### PR TITLE
Use kotlin.test instead of JUnit

### PR DESCRIPTION
**Pull request by riQQ**
Almost everything works, but there is one new test failure in `androidTest` `NoteQuestsHiddenDaoTest.getNewerThan` on a Pixel 4 emulator that I don't know what it's caused by:

```
java.lang.NoSuchMethodError: No static method boxLong(J)Ljava/lang/Long; in class Lkotlin/coroutines/jvm/internal/Boxing; or its super classes (declaration of 'kotlin.coroutines.jvm.internal.Boxing' appears in /data/app/~~Cmbt4P5atgm8GMNc69RGiA==/de.westnordost.streetcomplete.debug-n9y365mjtzOc6KdZczYHAg==/base.apk)
at de.westnordost.streetcomplete.data.osmnotes.notequests.NoteQuestsHiddenDaoTest$getNewerThan$1.invokeSuspend(NoteQuestsHiddenDaoTest.kt:49)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:254)
at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:595)
at kotlinx.coroutines.EventLoopImplBase$DelayedResumeTask.run(EventLoop.common.kt:493)
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
at de.westnordost.streetcomplete.data.osmnotes.notequests.NoteQuestsHiddenDaoTest.getNewerThan(NoteQuestsHiddenDaoTest.kt:43)
```

The error occurs in line 49 `assertEquals(2L, result.noteId)`.

https://github.com/streetcomplete/StreetComplete/blob/7063485528c4cbb2a56c9cc1381cc18db341f3f9/app/src/androidTest/java/de/westnordost/streetcomplete/data/osmnotes/notequests/NoteQuestsHiddenDaoTest.kt#L43-L50

And another question regarding code style of imports and consistency.
Some files use star import à la `import org.junit.Assert.*`. Should this be kept, all files changed to star import or all files changed to explicit imports?

### CODE REVIEW

**Comment by westnordost** [comment]
Oh, cool!

For me, * imports for the test framework stuff is fine.

**Comment by riQQ** [comment]
So change all the test imports to `import kotlin.test.*`?

What do we do about the new test failure? Any idea?

**Comment by westnordost** [comment]
It's up to you, I'm fine with it either way.

Especially for tests though, IMO it is not necessary to know where the particular `assert` is coming from, as it is used pretty much in every test function.

Regarding the test failure - it concerns the `androidTests`, no? I understand that you only changed the `tests`. Anyway, I guess it is some kind of auto-boxing failure. I may have a look at that some time later. To be honest, I kind of ... don't like that all the database tests are in `androidTest` as if it was dependent on Android. Well, it kind of is a little bit, since the SQLite API is built-in into Android without an extra dependency. But with relatively little effort, I think all those database tests could be migrated into the normal test code.

**Comment by riQQ** [comment]
> Regarding the test failure - it concerns the `androidTests`, no? I understand that you only changed the `tests`. 
Yes and yes

> Anyway, I guess it is some kind of auto-boxing failure.
Any hint on where to read up on this? A quick search didn't return anything useful.

**Comment by westnordost** [comment]
Java auto boxes (and unboxes) primitive types like long into objects like Long in some circumstaces. But anyway, its just a hunch, it could not be related at all.

Am 28. August 2023 17:46:17 MESZ schrieb riQQ ***@***.***>:

**Review by westnordost — APPROVED** [review]

**Comment by FloEdelmann** [comment]
(Just assigning the people who did the work to the completed ticket so that https://github.com/orgs/streetcomplete/projects/1/views/1 looks nicer :-) )

**Pull request merged**
