### PR TITLE
add camera type quest

### LINKED ISSUE #87: Surveillance camera properties
Support surveillance camera properties as is also discussed in https://github.com/DaylightingSociety/WhereAreTheEyes/issues/3 and https://github.com/DaylightingSociety/WhereAreTheEyes/issues/15 and specifically https://github.com/DaylightingSociety/WhereAreTheEyes/issues/3#issuecomment-264463712 and https://kamba4.crux.uberspace.de/

### PR DESCRIPTION
**Pull request by Helium314**
This is an update of @Binnette's camera type PR #299, fixes #87
I changed the wording and extracted the quest icon from the svg file.

* I don't have much experience und working with vector graphics. The extracted quest icon looks ok, but maybe it should be checked.
* I limited the cameras to `surveillance ~ public|outdoor|traffic` to exclude cameras in shops.
* Would re-survey make sense? Could be used instead of adding cameras to the check existance quest.
* Cameras are often high up (especially the ones mounted on poles), so maybe a hint should be added to the text.
* Icons and white text don't get along very well, this needs to be fixed (see screenshot)

Screenshot_20210507-110650_Street�Complete

### CODE REVIEW

**Comment by TurnrDev** [comment]
A solution to the text could be to add a grey background to the option pictures :)

**Comment by westnordost** [comment]
> Would re-survey make sense? Could be used instead of adding cameras to the check existance quest.

No, better add it to check existance quest. The camera types don't change, what changes is if they are there at all or not.
The duration for rechecking should be very long, not because it is not something that might be volatile, but the up-to-dateness of this information is very unimportant as the data is exclusively used for "showing that there is so much of it!" and (hopefully) not by other people who have an interest to avoid or something the surveillance.

> icons & white text

Add 
```kotlin
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        imageSelector.cellLayoutId = R.layout.cell_icon_select_with_label_below
    }
```

**Comment by Helium314** [comment]
Thanks! Then I guess it's ready for review...

**Comment by westnordost** [comment]
Ok, but there is no rush, it will not go into v32 but into v33.

The icon for the camera is really fugly though. Blocky, too thin lines, not recognizable on low resolution. Looking at https://www.google.com/search?q=icon+surveillance&tbm=isch ,  I'd probably replace it with a (self-drawn) icon that is similar to the one from iconexperience and/or is inspired by a couple of others. Or if you like and you are able, you could give it a try yourself.

**Comment by westnordost** [comment]
Also, the icon from the old PR was really nice. Alternatively, a "big brother" kind of eye would also look nice IMO

**Review by westnordost — APPROVED** [review]
Code looks fine 👍

**Comment by Helium314** [comment]
> Also, the icon from the old PR was really nice. Alternatively, a "big brother" kind of eye would also look nice IMO

actually this _is_ the icon from the old PR, but the one added to [quest_icons.svg](https://github.com/streetcomplete/StreetComplete/pull/299/files#diff-85f51c694a65e4eae5e63b8bb238cd69e38a76cf38677c2c730c78636bddca9d) is different from the one in the screenshot (which is in the PR as .png only)

**Comment by smichel17** [comment]
> https://www.google.com/search?q=icon+surveillance&tbm=isch

There was a typo in your url. Fixed: https://duckduckgo.com/?q=icon+surveillance&iax=images&ia=images

**Comment by westnordost** [comment]
Alright, as there seem to be no big bugs in v32 left, let's merge all the stuff for v33

**Comment by peternewman** [comment]
> > Also, the icon from the old PR was really nice. Alternatively, a "big brother" kind of eye would also look nice IMO
> 
> actually this _is_ the icon from the old PR, but the one added to [quest_icons.svg](https://github.com/streetcomplete/StreetComplete/pull/299/files#diff-85f51c694a65e4eae5e63b8bb238cd69e38a76cf38677c2c730c78636bddca9d) is different from the one in the screenshot (which is in the PR as .png only)

Looking at #2754 @Helium314 has flagged up that this PR hasn't added something to https://github.com/streetcomplete/StreetComplete/tree/master/res/graphics/quest%20icons as camera_type.svg as the original icon for this quest (which every other quest has)

**Comment by westnordost** [comment]
I am creating the icon right now, stay tuned... taking longer than expected.

Also I noticed that hte licenses are missing. And I can't find the used picture anywhere, so maybe I should redo the dome-picture too

**Comment by codeinabox** [comment]
Thank you for this feature! One question I have is what about when there are multiple cameras on a mast / pole where one is fixed and the other is a dome camera? I have spotted a few in London

**Comment by westnordost** [comment]
Hmm i suppose that should be two cameras then

**Pull request merged**
