### PR TITLE
Change bikeway references to cycleway

### PR DESCRIPTION
**Pull request by TurnrDev**
No real reason other than it bothered me that it was bikeway 🤷🏻

### CODE REVIEW

**Comment by TurnrDev** [comment]
tested at 8a66df4b9e3c93eb5ee53334c8670e3aaf848fd8 - builds

**Comment by westnordost** [comment]
Why, is bikeway not a word?

**Comment by TurnrDev** [comment]
Never heard it before today, but it might be. I saw the two terms used interchangeably in the same module and just found it a little confusing so thought it would make sense to fit the key?

**Comment by westnordost** [comment]
Okay 🤷

**Review by westnordost — APPROVED** [review]

**Pull request merged**
