### PR TITLE
shelter_type quest

### LINKED ISSUE #4418: New quest: What type of shelter is this? (Specifying `shelter_type=*`)
### General
Affected tag(s) to be modified/added: [`shelter_type`](https://wiki.openstreetmap.org/wiki/Key:shelter_type)
Question asked: **What type of shelter is this?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** Any `amenity=shelter` that doesn't have a `shelter_type` tag yet.

**Metadata needed:** None

**Proposed UI:** Multiple choice with example images.

### PR DESCRIPTION
**Pull request by mcliquid**
Fix #4418 

- Probably it still needs a correction with the pictures, since not all licenses fit here.
- The Quest Icon is still provisional, I will try to adapt this better to the others.
- I have already tested the new Quest and look forward to feedback!

### CODE REVIEW

**Comment by westnordost** [comment]
Just a very rough preliminary review:

Choices:
The pictures look kind of odd - some seem to be very specific and I wouldn't know what exactly puts them apart. Is the field shelter only for animals or for humans too (people working on the field)? What sets apart a gazebo from a picnic shelter? What sets apart a picnic shelter from a sun shelter? A weather shelter?
If possible, this should be selectable without long descriptions. This may not be possible. And it may not even be possible to come up with a resonable definition - but in that case, the tagging scheme is bad and it should not even be a quest.

Pictures:
- try to find most representative pictures. E.g.: So, if the shelter is kunterbunt, it's a "basic hut"? The pictures should only show what each category differentiates it from the others and should have no other characteristics that could be mistaken for being relevant. This is the other hard part of creating (such) a quest. Finding good pictures.
- sources+licenses for pictures are missing
- the sizes for the pictures are not correct. It should be 384 for xxhdpi, 256 for xhdpi, 192 for hdpi, 128 for mdpi. Also, check if the JPEG compression quality is not unnecessarily high

**Comment by andrewharvey** [comment]
sad to see no support for rock_shelter, would you accept a contribution adding it?

**Comment by matkoniecz** [comment]
> In general, I have the feeling that shelter_type is one of those "free form" tags with a bottomless (and unordered) pit of possible values, which would somewhat disqualify it for a quest.

Still, there could be a limited set of values covering vast majority (like `building` value quest where some oddities remain for notes, but quest remains viable)

**Comment by matkoniecz** [comment]
>  For example, I'm still not quite clear what the difference between Pavilion and Gazebo should be.

And trying to find out such things is a great way to discover badly defined tagging schemes (see my tagging list postings about taps and drinking fountains + OSM Wiki activity on related pages)

**Comment by westnordost** [comment]
> To make a long story short: Is it even worth working on the quest then? According to my understanding of your answer, it needs an intensive work in advance, which includes not only new images but also a complete rebuilding of the wiki page? And I have never dealt with tagging definition, wiki or tagging ML. Then I would rather only choose quests that already have the "new quest" approved flag.

I'd say it is not worth working on it (further) until this point has been discussed. IMO Mateusz tagging of the issue as "new quest" was a little preliminary.

**Comment by riQQ** [comment]
The link for `basic_hut` is broken.

**Comment by westnordost** [comment]
Most pictures are definitely better, however:

> picnic_shelter

The picnic tables will barely be visible in the small picture displayed in the app

> weather_shelter vs lean_to

So lean_to is not primarily a construction trait but made as a weather-for-overnight-stay shelter?

> weather_shelter vs pavilion

So, the difference is that the former is defined by its function and the latter is defined by its architecture? (Because obviously the latter also protects against weather)

> basic_hut vs weather_shelter

So the basic hut is basically an "upgrade" to the weather shelter, in that it has 4 walls?

> sun_shelter vs weather_shelter

Why wouldn't a sun shelter not also protect against rain?

> field_shelter

So "field shelters" for farmers would be tagged as `weather_shelter` instead?

---

Hm well, as I wrote, the tag contains a wild mix of architecture type (pavillon, gazebo), function (field shelter, picnic shelter, ...) and features (walls or not / how well protected against bad weather). This is quite a bad prerequisite for a quest.

**Comment by mnalis** [comment]
Yeah, i think it needs massive reduction of answers to be usable quest. Basically, as far as data consumer usability of the tag goes, I see following:
- just the roof
- roof and 3 sides
- roof and fully enclosed on 3.5-4 sides (e.g. `basic_hut`)
- not-for-humans
- (maybe also that `rock_shelter` cave as an extra, as it is not a modern civilization structure, so unlikely to be mistaken with others)

and then go for the most generic/popular of the answers, and go with `leave a note` for the others. 

I mean, pictures of `picnic_shelter` , `gazebo`, `weather_shelter`, `pavilion`, `sun_shelter` all look the same to me. I certainly wouldn't want to have to try to distinguish between all of them; they're all just a roof on some sticks! They'll protect me from both sun and rain, but not from heavy winter wind. So what does it matter? (only minor difference is that `picnic_shelter` _might imply_ table+bench, but I usually just use `leisure=picnic_table`+`covered=yes` for those anyway)

**Comment by westnordost** [comment]
Well, I didn't do research, but my gut feeling is that this is not enough, because simply the presence of these topsy-turvy tag values is a strong indicator for those values being poorly defined. I.e. that some/many `weather_shelter`s will actually have walls etc.

Also, we are dealing with a tag that is well in use already. I do not think we can pick a few values we want to support and drop the rest. 50% of all shelter_types tagged are public transport shelters, certainly nobody would be happy if users through streetcomplete started tagging those with `weather_shelter` because they protect from the weather. Same with other unique shelter types such as `pavillion` 

etc

**Comment by mnalis** [comment]
My main concern is **how to convey all that information for the very similar (and sometimes overlapping definitions) of those structures to the average SC user**, with just a picture and few words (instead of several must-read full wiki pages with examples). 

While I have mapped some shelters in more advanced OSM editors (JOSM, Vespucci...) I am not an huge expert in them. That being said, I have read their wiki pages few times, and mapped what I needed in the past.

But even with such above-average OSM shelter raw tag experience, I for one would certainly be confused what to map exactly if SC were to ask me  such _unabridged list of tags_ as suggested in https://github.com/streetcomplete/StreetComplete/pull/4428#issuecomment-1263878948. Unless of course few words over those pictures could define key differences between them in very clear and concise way (which seems very hard task to me - but then again _clarity in shortness_ has never been my forte)

**Comment by westnordost** [comment]
I'll close this then and the associated quest then. Sorry that you spent time on implementation already

**Comment by matkoniecz** [comment]
I am sorry that I misjudged situation and marked it as a viable quest :(

**Pull request closed without merging**
