### PR TITLE
Add santiary dump station fee quest (Needs Icon)

### PR DESCRIPTION
**Pull request by catdogmat**
This quest applies to ~50% of all sanitary dump stations on OSM. This quest will ask "Does this Sanitary Dump Station require a fee?"

This PR needs a icon.

### CODE REVIEW

**Comment by qugebert** [comment]
why not just extend the general_fee quest?

**Comment by catdogmat** [comment]
thanks for the heads up

**Comment by HolgerJeromin** [comment]
New PR in #5332

**Comment by catdogmat** [comment]
Reopen as people said this is a better solution

**Comment by FloEdelmann** [comment]
see https://github.com/streetcomplete/StreetComplete/pull/5332#issuecomment-1782643189

**Pull request closed without merging**
