### PR TITLE
Crossing island quest with footways

### PR DESCRIPTION
**Pull request by dbdean**
WIP on allowing crossing:island quests when footways/cycleways etc are mapped separately. 

See https://github.com/streetcomplete/StreetComplete/issues/2454 for issue.

### CODE REVIEW

**Comment by westnordost** [comment]
I read up on the issue and I can't think of an example now where the road is **not** oneway but a footway that crosses the road should not have a `crossing:island=yes/no`. Or did I miss something?

So from my point of view, this could be merged. @kmpoppe @matkoniecz any comments?

Why is this WIP?

**Comment by dbdean** [comment]
I hadn't tested it a the time of creating the PR. Now that I have run it on my phone and done a bit of mapping, I'm happy with the way it works now. I've removed the WIP label and am happy for this to be merged if @kmpoppe and/or @matkoniecz have no objections.

**Comment by matkoniecz** [comment]
Maybe it was intended to exclude small roads?

In any case, I am not opposed to such change in oneway filtering.

**Comment by matkoniecz** [comment]
I have not tested this PR but I see no problems here.

**Comment by westnordost** [comment]
Okay, let's merge it then, thank you!

**Pull request merged**
