### PR TITLE
Ask AddEntrance for multipolygon buildings

### PR DESCRIPTION
**Pull request by Helium314**
see #4968

### CODE REVIEW

**Comment by matkoniecz** [comment]
Have you tested it? What about nonmultipolygon relation members? See http://overpass-turbo.eu/s/1ucd

**Comment by Helium314** [comment]
It will also find members of non-multipolygon relation buildings, as I did not change the filter

> Have you tested it? 

yes

**Comment by matkoniecz** [comment]
I guess that ideally there would be also extra filter to get rid of unwanted relations (I will add it unless you figure out how to access tags in that steps - or maybe nonmultipolygons relations are not downloaded/stored by SC anyway).

**Comment by Helium314** [comment]
Adding `and (!type or type = multipolygon)` to the filter should work, as relations are supposed have a type.

**Comment by matkoniecz** [comment]
Again , feel free to add one if you want (or I will add after I dig out of current TODO pile) - but maybe a test case in tests would be nice, with specifically a relation?

**Comment by Helium314** [comment]
btw it would be the test file is not found automatically by Android Studio because of the name "AddBuildingEntranceTest", same for entrance ref quest.

**Comment by matkoniecz** [comment]
> btw the test file is not found automatically by Android Studio because of the name "AddBuildingEntranceTest", same for entrance ref quest.

fixed

> same for entrance ref quest.

I also added functionality for this one, based on your code.

**Pull request merged**
