### PR TITLE
Use doAfterTextChanged instead project defined one

### PR DESCRIPTION
**Pull request by ebraminio**
doAfterTextChanged is provided by core-ktx and can replace
project defined TextChangedWatcher now.

### CODE REVIEW

**Review by westnordost — APPROVED** [review]
ok, seems reasonable

**Comment by westnordost** [comment]
Ah, I thought this was from @FloEdelmann , so there is a certain muscle memory to merge his PRs. 

Firstly, thank you for your contribution! And the compulsory question: Did you test it?

**Comment by FloEdelmann** [comment]
What an honour :blush: 

I just had a quick glance (and it looked fine), but since you @westnordost added the `TextChangedWatcher`, I thought you should have a look at this, too.

I didn't test this change though. @ebraminio did you? (i.e. fill out text in the emulator or on a real device to see if the callback is activated like expected)

**Comment by ebraminio** [comment]
> I didn't test this change though. @ebraminio did you? (i.e. fill out text in the emulator or on a real device to see if the callback is activated like expected)

Here is a screencast of what happens on https://github.com/streetcomplete/StreetComplete/pull/3929/files#diff-99c3bc698c42a0e9a3118ea77c24b8762876b039c11e7ff0b447c45b0dcdf91fR38 

https://user-images.githubusercontent.com/833473/160813191-0a0ba6e1-9c2f-40a0-baa3-0d17a76371b8.mov

But as I'm not a hardcore user myself sure a retesting won't harm 😊 Btw the UI looks creative and fantastic, congrats to you for developing this

**Comment by westnordost** [comment]
That looks like the correct behavior, thank you!

**Pull request merged**
