### PR TITLE
Implement Login screen in compose

### LINKED ISSUE #5711: Google Third Party Login doesn't log you in
**Description**
I'm a new user looking to contribute, I've been asked to log into the app. When I choose the Google alternative, it opens the Google authentication page where it asks for the Email address and credential, however, once these have been provided the app reverts back to the Map but I'm not logged in.

**How to Reproduce**
1. Open the StreetComplete app
2. Click on the Hamburger menu and select "My Profile"
3. Click on "Login"
4. "Log in to OpenStreetMap to access StreetComplete" window should appear, choose the Google image under "Alternatively, use a third party to login" section towards the bottom.
5. Provide necessary details for the Google account, confirming any MFA actions (for me, this is a 2-step using the Device I have StreetComplete installed on)
6. You're taken back to the map, but are not logged in (checking via Hamburger Menu > My Profile)

**Expected Behavior**
Profile to be created and to be signed in.

**Versions affected**
Android 14 (Build AP2A.240605.024), StreetComplete v58.0

### LINKED ISSUE #5724: Login page crash
**How to Reproduce**

1. Be logged out
2. Answer quests
3. Click upload icon
4. Click OK on login popup
5. Login page loads (white page, blue login button), but crashes instantly

SC 58
```
java.lang.IllegalStateException: Fragment LoginFragment{1bc0d7a} (997390a5-dfea-44e1-b0f0-b2b2aa191550) did not return a View from onCreateView() or this was called before onCreateView().
	at androidx.fragment.app.Fragment.requireView(Unknown Source:31)
	at de.westnordost.streetcomplete.util.FragmentViewBindingPropertyDelegate.getValue(SourceFile:0)
	at de.westnordost.streetcomplete.screens.user.login.LoginFragment.getBinding(Unknown Source:7)
	at de.westnordost.streetcomplete.screens.user.login.LoginFragment.access$getBinding(Unknown Source:0)
	at de.westnordost.streetcomplete.screens.user.login.LoginFragment$OAuthWebViewClient.onPageStarted(Unknown Source:7)
	at WV.iK.c(chromium-TrichromeWebView6432.apk-stable-647812433:16)
	at WV.R5.handleMessage(chromium-TrichromeWebView6432.apk-stable-647812433:505)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

Log:
2024-07-07T09:56:37.962: I [Preloader] Loaded country boundaries in 0.1s
2024-07-07T09:56:38.274: I [Preloader] Loaded features dictionary in 0.4s
2024-07-07T09:56:38.275: I [Preloader] Preloading data took 0.4s
```

SCEE 58
```
java.lang.IllegalStateException: Fragment LoginFragment{3eabb36} (dc29815f-3312-433f-b946-5fb625fb007a) did not return a View from onCreateView() or this was called before onCreateView().
at androidx.fragment.app.Fragment.requireView(Fragment.java:2063)
at de.westnordost.streetcomplete.util.FragmentViewBindingPropertyDelegate.getValue(ViewBinder.kt:80)
at de.westnordost.streetcomplete.screens.user.login.LoginFragment.getBinding(LoginFragment.kt:32)
at de.westnordost.streetcomplete.screens.user.login.LoginFragment.access$getBinding(LoginFragment.kt:27)
at de.westnordost.streetcomplete.screens.user.login.LoginFragment$OAuthWebViewClient.onPageStarted(LoginFragment.kt:124)
at WV.iK.c(chromium-TrichromeWebView6432.apk-stable-647812433:16)
at WV.R5.handleMessage(chromium-TrichromeWebView6432.apk-stable-647812433:505)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7940)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ExecInit.main(ExecInit.java:49)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

Log:
2024-07-04T22:19:34.628: I [MainFragment] onStart (add listeners)
2024-07-04T22:19:34.635: I [MainFragment] onResume
2024-07-04T22:19:38.996: I [MainFragment] onPause
2024-07-04T22:19:40.162: I [MainFragment] onStop (remove listeners)
2024-07-04T22:19:40.162: I [MainFragment] onSaveInstanceState
2024-07-04T22:19:41.350: I [MainFragment] onAttach
2024-07-04T22:19:41.357: I [MainFragment] onCreate
2024-07-04T22:19:41.441: I [MainFragment] onCreateView
2024-07-04T22:19:41.464: I [MainFragment] onViewCreated
2024-07-04T22:19:41.517: I [MainFragment] onViewStateRestored
2024-07-04T22:19:41.522: I [MainFragment] onStart (add listeners)
2024-07-04T22:19:41.535: I [MainFragment] onResume
2024-07-04T22:19:41.652: I [Preloader] Loaded country boundaries in 0.1s
2024-07-04T22:19:41.999: I [Preloader] Preloading data took 0.5s
2024-07-04T22:19:41.999: I [Preloader] Loaded features dictionary in 0.5s
2024-07-04T22:19:48.681: I [MainFragment] onPause
2024-07-04T22:20:12.372: I [MainFragment] onCreate
2024-07-04T22:20:12.372: I [MainFragment] onAttach
2024-07-04T22:20:12.401: I [MainFragment] onCreateView
2024-07-04T22:20:12.439: I [MainFragment] onViewCreated
2024-07-04T22:20:12.507: I [MainFragment] onViewStateRestored
2024-07-04T22:20:12.516: I [MainFragment] onStart (add listeners)
2024-07-04T22:20:12.534: I [MainFragment] onResume
2024-07-04T22:20:12.647: I [Preloader] Loaded country boundaries in 0.1s
2024-07-04T22:20:13.025: I [Preloader] Loaded features dictionary in 0.5s
2024-07-04T22:20:13.026: I [Preloader] Preloading data took 0.5s
2024-07-04T22:20:17.283: I [MainFragment] onPause
2024-07-04T22:20:18.054: I [MainFragment] onStop (remove listeners)
2024-07-04T22:20:18.055: I [MainFragment] onSaveInstanceState
2024-07-04T22:20:22.604: I [MainFragment] onStart (add listeners)
2024-07-04T22:20:22.645: I [MainFragment] onResume
2024-07-04T22:20:25.349: I [MainFragment] onPause
2024-07-04T22:20:37.088: I [MainFragment] onCreate
2024-07-04T22:20:37.089: I [MainFragment] onAttach
2024-07-04T22:20:37.109: I [MainFragment] onCreateView
2024-07-04T22:20:37.156: I [MainFragment] onViewCreated
2024-07-04T22:20:37.202: I [MainFragment] onViewStateRestored
2024-07-04T22:20:37.205: I [MainFragment] onStart (add listeners)
2024-07-04T22:20:37.220: I [MainFragment] onResume
2024-07-04T22:20:37.400: I [Preloader] Loaded country boundaries in 0.2s
2024-07-04T22:20:37.732: I [Preloader] Preloading data took 0.5s
2024-07-04T22:20:37.732: I [Preloader] Loaded features dictionary in 0.5s
2024-07-04T22:20:40.849: I [MainFragment] onPause
2024-07-04T22:20:40.889: I [MainFragment] onStop (remove listeners)
2024-07-04T22:20:40.895: I [MainFragment] onSaveInstanceState
2024-07-04T22:20:43.332: I [MainFragment] onCreate
2024-07-04T22:20:43.332: I [MainFragment] onAttach
2024-07-04T22:20:43.407: I [MainFragment] onCreateView
2024-07-04T22:20:43.448: I [MainFragment] onViewCreated
2024-07-04T22:20:43.491: I [MainFragment] onViewStateRestored
2024-07-04T22:20:43.492: I [MainFragment] onStart (add listeners)
2024-07-04T22:20:43.498: I [MainFragment] onResume
2024-07-04T22:20:43.709: I [Preloader] Loaded country boundaries in 0.2s
2024-07-04T22:20:44.060: I [Preloader] Loaded features dictionary in 0.5s
2024-07-04T22:20:44.060: I [Preloader] Preloading data took 0.6s
2024-07-04T22:20:47.311: I [MainFragment] onPause
2024-07-04T22:20:54.360: I [MainFragment] onAttach
2024-07-04T22:20:54.361: I [MainFragment] onCreate
2024-07-04T22:20:54.392: I [MainFragment] onCreateView
2024-07-04T22:20:54.429: I [MainFragment] onViewCreated
2024-07-04T22:20:54.483: I [MainFragment] onViewStateRestored
2024-07-04T22:20:54.486: I [MainFragment] onStart (add listeners)
2024-07-04T22:20:54.502: I [MainFragment] onResume
2024-07-04T22:20:54.613: I [Preloader] Loaded country boundaries in 0.1s
2024-07-04T22:20:54.984: I [Preloader] Loaded features dictionary in 0.5s
2024-07-04T22:20:54.984: I [Preloader] Preloading data took 0.5s
2024-07-04T22:20:58.255: I [MainFragment] onPause
2024-07-04T22:20:59.030: I [MainFragment] onStop (remove listeners)
2024-07-04T22:20:59.032: I [MainFragment] onSaveInstanceState
2024-07-04T22:21:01.361: I [MainFragment] onStart (add listeners)
2024-07-04T22:21:01.367: I [MainFragment] onResume
2024-07-04T22:21:06.638: I [MainFragment] onPause
```

**Expected Behavior**

The webview should load with the osm.org login page and allow me to authenticate.

**Versions affected**
SC 58.0
SC 58.1
SCEE 58.0
Android 13 (**GrapheneOS**)

### PR DESCRIPTION
**Pull request by westnordost**
fixes #5724
fixes #5711 

Note that if the login activity is destroyed and recreated, the login flow will begin from the start.

This can happen if both the system is on low resources and the user needs to tab out of the app for two factor authorization*, i.e. when using a Google account. So if this continues to be a problem, maybe we need to change to in-browser authentication instead of a webview.

*funny, how is it two-factor if it is both on the same phone... oh well...

### CODE REVIEW

**Comment by rugk** [comment]
AFAIK a web view is anyway not recommend both for security reasons and from the RFC for OAuth:
> Considering these security concerns, WebView is not recommended for OAuth implementation in mobile apps.

> “Native apps MUST NOT use embedded user-agents to perform authorisation requests and allow that authorisation endpoints MAY take steps to detect and block authorisation requests in embedded user-agents.”

**Comment by westnordost** [comment]
Yes, not recommended. But allowed.

Yet, everyone is doing it. Checked Josm, Vespucci, EveryDoor, Openstop, OrganicMaps (organicmaps and josm being the worst offenders here).

When one looks for guides how to implement Oauth2 authorization for iOS for example, they all use WebViews. This information is very old, maybe they changed it, but IIRC Apple recommended or required the use of WebViews over anything with browsers for authorization at one point.

The reason for why SC is doing it is because some people don't use the standard browsers like Chrome but e.g the LineageOS browser, Brave, the duckduckgo browser, etc pp. If this kind of per-url-forwarding-to-apps is not implemented correctly in whatever esoteric browser the user has installed as his default, authorization won't work while looking as if it is a problem of the app.
I mentioned the LineageOS browser because last time I checked, it didn't implement it correctly and the issue remained for YEARS, maybe is still unfixed/unimplemented.

**Comment by westnordost** [comment]
Correction: EveryDoor and OpenStop both use the browser.

**Comment by westnordost** [comment]
I tested it with some browsers.

Of Chrome, Firefox, Samsung Internet, Jelly (Default Browser in LineageOS), Opera, DuckDuckGo Browser and Brave,

- Jelly continues to show an error page instead

- DuckDuckGo asks whether the URL should be opened in an application and it only works if the user selects "yes". This WILL confuse users

**Pull request merged**
