### PR TITLE
Fix failing unit tests build

### PR DESCRIPTION
**Pull request by neonowy**
Was interested in contributing to the project, but stumbled upon compiler errors after trying to run `testDebugUnitTest`.
Seems like some tests were not updated in #5280.

BTW, would you be interested in a separate PR for running test job for every commit on `master`? Seems like the existing test job definition is outdated/not used.

### CODE REVIEW

**Comment by FloEdelmann** [comment]
Oh thanks, I indeed forgot to check the tests!

**Comment by riQQ** [comment]
> BTW, would you be interested in a separate PR for running test job for every commit on `master`? Seems like the existing test job definition is outdated/not used.

See #2522 :(

**Comment by matkoniecz** [comment]
> See https://github.com/streetcomplete/StreetComplete/issues/2522 :(

It seems that

> Also, currently some Android tests always fail, see https://github.com/streetcomplete/StreetComplete/issues/2028 so the CI would just report for everything that tests fail. That's not useful. It would be useful to do something about https://github.com/streetcomplete/StreetComplete/issues/2028 or its successor-ticket.

is no longer applying

**Comment by riQQ** [comment]
But you left out the first line of westnordost's post:
> I don't see the necessity for this. I do run Android lint, the tests etc before each release.

**Comment by matkoniecz** [comment]
Maybe that was overintepretation... I initially thought that it was expressing that it is not strictly necessary AND blocked.

Though "I don't see the necessity for this" can also mean that it is simply unwanted at all.

**Pull request merged**
