### PR TITLE
add beverage cartons as option below "plastic"

### LINKED ISSUE #2502: recycling quests: clear/colored glass, carton
**Use case**

recycling quest is missing local features such as specific containers for clear and colored glass, tetrapack cartons, and old toys containers which are often together with containers for old clothes.. what do you think?
**Proposed Solution**

### PR DESCRIPTION
**Pull request by westnordost**
fixes #2502

### CODE REVIEW

**Review by FloEdelmann — COMMENTED** [review]
Nice illustration! As a whole, I really like the visual style of all the graphics in the app :)

**Comment by Helium314** [comment]
Could you please change this in a way that allows selecting plastic bottles and beaverage cartons? This is not possible at the moment.
Contrary to what it indicated by the images, 'plastic packaging' is not suitable if only plastic bottles and beaverage cartons are allowed, see https://www.wien.gv.at/umwelt/ma48/beratung/muelltrennung/plastikflaschen/plastikflaschen.html where blister packaging is explicitely excluded.

**Comment by westnordost** [comment]
Not only that but much more

https://www.wien.gv.at/umwelt/ma48/beratung/muelltrennung/plastikflaschen/gelbersack/index.html

Shampoo bottles, yogurt cups...

Sounds like plastic packaging with a few exceptions to me

Am 18. Februar 2021 12:54:30 MEZ schrieb Helium314 <notifications@github.com>:
>Could you please change this in a way that allows selecting plastic
>bottles and beaverage cartons? This is not possible at the moment.
>Contrary to what it indicated by the images, 'plastic packaging' is not
>suitable if only plastic bottles and beaverage cartons are allowed, see
>https://www.wien.gv.at/umwelt/ma48/beratung/muelltrennung/plastikflaschen/plastikflaschen.html
>where blister packaging is explicitely excluded.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/pull/2580#issuecomment-781291012

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Helium314** [comment]
Yes, this was just one example to show why I would like to select 'plastic bottles' and 'beaverage cartons', but can't select 'plastic packaging'

**Comment by westnordost** [comment]
Yeah but to select just these two would also not be correct. What is the common tagging practice for tagging gelber sack containers in Wien?

Am 18. Februar 2021 13:37:01 MEZ schrieb Helium314 <notifications@github.com>:
>Yes, this was just one example to show why I would like to select
>'plastic bottles' and 'beaverage cartons', but can't select 'plastic
>packaging'
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/pull/2580#issuecomment-781313351

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Helium314** [comment]
Selecting those two (and cans) would not be complete, but at least not wrong (in contrast to 'plastic packaging'). And I think it's ok to not catch everything that goes into a container, but there shouldn't be anything tagged that doesn't go in there.

Gelber Sack is not available as public container, only the similar Gelbe Tonne.
What goes in there changed several times in the past few years, so I guess many container nodes are outdated. There is no consistent tagging.
The metal part is inconsistent (cans and _small_ scrap metal allowed, so sometimes you find scrap metal tagged).
The plastic part is inconsistent (usually plastic packaging vs plastic bottles, maybe plastic if the container hasn't been updated in many years)
Beverage cartons are usually not tagged at all.

**Comment by westnordost** [comment]
> Gelber Sack is not available as public container, only the similar Gelbe Tonne.

Okay, then I can close this because this is not relevant for the quest.

**Comment by westnordost** [comment]
Hm currently the pic für "plastic packaging" includes a bottle and a carton. I guess if what @Helium314 wants is included, then that option must get a new pic. Specifically, it needs some other "plastic packaging" item in the icon. Any ideas what kind of motive would be typical and easy to recognize?

**Comment by Helium314** [comment]
Maybe a bag of potato chips?

**Pull request merged**
