### PR TITLE
property defining changeset comments is now named changesetComment 

### PR DESCRIPTION
**Pull request by matkoniecz**
See say https://wiki.openstreetmap.org/wiki/Good_changeset_comments

I think that there is no good reason to use `commitMessage` name

Main negative is that merging it will break unmerged quest PRs (and #3648 which triggered it).

### CODE REVIEW

**Comment by matkoniecz** [comment]
I can redo it and push straight to master branch after quests are merged - or push fixes to quest branches.

**Comment by naposm** [comment]
> I can redo it and push straight to master branch after quests are merged - or push fixes to quest branches where authors enabled this option.

For #2822 I think the option is enabled but can do it myself once this gets merged :+1:

**Comment by matkoniecz** [comment]
@westnordost Heh, I promised and I am not sure how I will do this.

Should I merge `master` onto `40` and then adjust new quests?

**Comment by westnordost** [comment]
I did this myself

**Pull request merged**
