### PR TITLE
Add Persian Translator

### PR DESCRIPTION
**Pull request by ahangarha**

### CODE REVIEW

**Comment by westnordost** [comment]
Thanks, Mostafa, and thank you for your translations so far!

I usually update the translator credits every few major versions, whenever I feel many strings have been added lately. For v31 this seems to be the case, so I'll do that again. (It's always a little time consuming to "fish" this info out from POEditor)

I also order the translators for each language roughly by contribution cound, which would put you at position 2 for Persian. 

Rather than merging this PR, I'll rather update the whole list in one go before I release v31.0 but if you don't mind, keep this PR open as a reminder.

**Comment by ahangarha** [comment]
Oh! I see

I thought I am left out. Then I close this PR. Is it fine?

**Comment by westnordost** [comment]
Id rather keep it open as a reminder so that i really do update that list before the release

On March 2, 2021 6:32:29 AM GMT+01:00, Mostafa Ahangarha <notifications@github.com> wrote:
>Oh! I see
>
>I thought I am left out. Then I close this PR. Is it fine?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/pull/2627#issuecomment-788611449

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
done

**Pull request closed without merging**
