### PR TITLE
Ask for pitch lit for nodes too

### PR DESCRIPTION
**Pull request by peternewman**
To match the base sport quest

Untested, but copied from the base sport one

### CODE REVIEW

**Comment by peternewman** [comment]
CC @eginhard

**Comment by matkoniecz** [comment]
@peternewman Can you test it?

**Comment by peternewman** [comment]
> @peternewman Can you test it?

Sorry I've still not got Android Studio installed and not really ready to start fighting with that yet, think of this more as an issue report with a suggested fix.

**Comment by matkoniecz** [comment]
Still very useful, thanks for submitting it!

**Comment by westnordost** [comment]
Fighting with it? You just install it. Or do you run some obscure operating system for which there is no installer?

**Comment by westnordost** [comment]
Android studio comes packaged with its own gradle

**Comment by westnordost** [comment]
Sorry, gotta revert that after all. Without seeing the outline of a sports pitch, it is often not really possible to see which pitch is meant. This is especially true for table tennis "pitches" but for others too, f.e. within a larger area where there are multiple pitches.

**Comment by peternewman** [comment]
> Sorry, gotta revert that after all.

Fair enough.

> Without seeing the outline of a sports pitch, it is often not really possible to see which pitch is meant. This is especially true for table tennis "pitches" but for others too, f.e. within a larger area where there are multiple pitches.

Doesn't this apply to https://github.com/streetcomplete/StreetComplete/blob/31a51693165996b4f79ff449f5667c36b1493bf9/app/src/main/java/de/westnordost/streetcomplete/quests/sport/AddSport.kt#L17 too then? i.e. shouldn't the type of sport and whether it's lit have the same challenges/limitations?

I guess this would be another good candidate for fixing via #2354 if that gets implemented at some point.

**Comment by westnordost** [comment]
Hmm... yeah, probably yes. I'll also remove `nodes` there.

**Comment by Helium314** [comment]
Would it be possible to check whether there are other `leisure = pitch` elements/nodes nearby, like it is done for the recycling quest? If there is only one within sth like 20-50 m, there should be no problem

**Comment by peternewman** [comment]
> Would it be possible to check whether there are other `leisure = pitch` elements/nodes nearby, like it is done for the recycling quest? If there is only one within sth like 20-50 m, there should be no problem

Sounds good, I'd pondered something similar when @westnordost mentioned it, but I didn't realise code for it already existed. I guess it would need to exclude nodes when there was a nearby node or way of the right type.

**Comment by westnordost** [comment]
I'd like to keep such distance checks to the necessities, because they are very CPU intensive to do (and I would like to not let the code grow too complex)

**Pull request merged**
