### PR TITLE
Ask for roof shape for all buildings with levels (except in low-rainfall countries)

### PR DESCRIPTION
**Pull request by dbdean**
As the value of `roof:levels` is no longer important for the `roof:shape` quest (except in low-rainfall countries), and as StreetComplete does not require `roof:levels` to be specified in the `building:levels` quest, I thought it would make sense to include buildings with no `roof:levels` tag in the `roof:shape` quest.

In order to not show this quest for all buildings, I have limited the quest to buildings that have had either the `building:levels` or the `roof:levels` tagged with some value.

For low rainfall countries, I think it should only show up if `roof:levels` exists and is not `0` - but I haven't tested this.

### CODE REVIEW

**Comment by westnordost** [comment]
Hmm, isn't this assuming that if `roof:levels` is not specified, it is 0?

>StreetComplete does not tag roof:levels=0

It does, if not this is a bug. It is just optional to fill out the roof levels

In any case, the changes are not complete, you missed to change `getApplicableElements`

**Comment by dbdean** [comment]
@westnordost, you are right - you can tag `roof:levels` = `0`, but specifying roof levels is optional in the quest, so I have never bothered putting in the `0`. I've updated my original comment to reflect this.

As for the change to `getApplicableElements`, it works fine for countries that don't have low rainfall as is 😄.

For countries that do have low rainfall, I need to fix the lines
```
                it.tags?.get("roof:levels") != "0" ||
                roofsAreUsuallyFlatAt(it, mapData) == false
```
But I don't really understand what the `it.tags?.get("roof:levels")` part would return if `roof:levels` is not tagged. I need to dig in a bit deeper so that I can say:
```
                (<roof:levels is tagged> && it.tags?.get("roof:levels") != "0") ||
                roofsAreUsuallyFlatAt(it, mapData) == false
```
I'll dig into the code a bit deeper and work it out this weekend, but any pointers would be appreciated.

**Comment by dbdean** [comment]
I have also noticed in testing this quest that asking for roof shape for buildings above about 3 levels is fairly pointless, as in most cases you can't see the roof, and it is probably flat anyway. That should probably be a different PR to fix that though.

**Comment by westnordost** [comment]
> But I don't really understand what the it.tags?.get("roof:levels") part would return if roof:levels is not tagged. I need to dig in a bit deeper so that I can say:

`null`

**Comment by dbdean** [comment]
@westnordost, I think this should work in low rainfall countries now. It should only show up there if `roof:shape` is tagged and is not `0`.

**Comment by westnordost** [comment]
Ok, looks good! The only thing that is missing now is to update the tests in `AddRoofShapeTest.kt`. In particular, in case all current tests already are green, to add two tests for the case that `roof:levels` is `null` - that it works the same as if the roof levels were zero.

**Comment by dbdean** [comment]
I can't seem to get the tests to run, even in the master branch:

```

org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class de.westnordost.streetcomplete.data.meta.CountryInfos.

If you're not sure why you're getting this error, please report to the mailing list.


Java               : 1.8
JVM vendor name    : JetBrains s.r.o
JVM vendor version : 25.242-b3-6222593
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 1.8.0_242-release-1644-b3-6222593
JVM info           : mixed mode
OS name            : Linux
OS version         : 5.4.0-65-generic


You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [class de.westnordost.streetcomplete.data.meta.CountryInfos, class java.lang.Object]

	at de.westnordost.streetcomplete.quests.roof_shape.AddRoofShapeTest.setUp(AddRoofShapeTest.kt:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: org.mockito.exceptions.base.MockitoException: Could not modify all classes [class de.westnordost.streetcomplete.data.meta.CountryInfos, class java.lang.Object]
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:152)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:365)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:174)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:376)
	... 36 more
Caused by: java.lang.IllegalStateException: 
Byte Buddy could not instrument all classes within the mock's type hierarchy

This problem should never occur for javac-compiled classes. This problem has been observed for classes that are:
 - Compiled by older versions of scalac
 - Classes that are part of the Android distribution
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:176)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClass(InlineBytecodeGenerator.java:152)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:37)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:34)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:152)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:365)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:174)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:376)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:32)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMockType(InlineByteBuddyMockMaker.java:197)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMock(InlineByteBuddyMockMaker.java:178)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:62)
	at org.mockito.Mockito.mock(Mockito.java:1908)
	at org.mockito.Mockito.mock(Mockito.java:1817)
	... 36 more
Caused by: java.lang.NoClassDefFoundError: Landroid/content/res/AssetManager;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at net.bytebuddy.description.type.TypeDescription$ForLoadedType.getDeclaredFields(TypeDescription.java:8418)
	at net.bytebuddy.dynamic.scaffold.InstrumentedType$Factory$Default$1.represent(InstrumentedType.java:363)
	at net.bytebuddy.ByteBuddy.redefine(ByteBuddy.java:745)
	at net.bytebuddy.ByteBuddy.redefine(ByteBuddy.java:720)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.transform(InlineBytecodeGenerator.java:249)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:173)
	... 50 more
Caused by: java.lang.ClassNotFoundException: android.content.res.AssetManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 63 more

```

Any ideas?

**Comment by westnordost** [comment]
Weird.... no, I don't have these problems.

It looks like it can't mock `CountryInfos` because it depends on `AssetManager` which is an Android-dependency. Even though it is a private field in that class and thus I wonder why it would be necessary for the mock framework to know anything about that class, I guess it is reasonable: Android-platform specific classes are not known in the normal Java environment.

However, this part in the gradle config:
```kotlin
    testOptions {
        unitTests {
            isReturnDefaultValues = true
        }
    }
```
should actually cause that outside of the Android environment, all Android classes are empty husks that return default values (`null`, `false`, `0`, ... ) on every method and do nothing. So somehow that is not working on your computer.

But I am at a loss why this might be the case.

Anyway, don't waste your time on this. You can just add the tests without running them and then I'll just execute the tests.

**Comment by westnordost** [comment]
I did this now. Turns out, there was a bug still.

**Comment by dbdean** [comment]
Thanks, @westnordost !

**Comment by tobylorenz** [comment]
This was exactly what I also wanted to get fixed in #2499. Good that this is done now.

**Pull request merged**
