### PR TITLE
Migrate from kaml to yamlkt

### LINKED ISSUE #5415: Multiplatform config file parsing
In various places, the app loads and parses some simple YAML files for configuration:

- a dictionary of street name abbreviations with their expansions (`abbreviations.yml`)
- a dictionary of version number to html fragments that are the changelog (`changelog.yml`)
- a list of main contributors (`credits_main.yml`)
- a list of side project contributors (`credits_projects.yml`)
- a list of all code contributors on github (`credits_contributors.yml`)
- a list of all art contributors (`credits_art.yml`)
- a dictionary of languages -> translator name -> number of translated words (`credits_translators.yml`)
- a dictionary of flag alignments by country code (`flag_alignments.yml`)
- a dictionary of various country properties (`<country code>.yml`)

#### keep YAML

Currently, [`com.charleskorn.kaml`](https://github.com/charleskorn/kaml) is used which is a plugin for `kotlinx-serialization`, however, no native targets are supported currently and noone is working on it at the time of writing (see https://github.com/charleskorn/kaml/issues/232). 

Another kotlin multiplatform yaml plugin exists, [`net.mamoe.yamlkt`](https://github.com/Him188/yamlkt), but according to the readme, it is (still) in alpha state. Multiline strings, which are currently used in `changelog.yml`, are "partially supported" since v0.13.0, not sure if this means whether the way multiline strings are used in this project is supported. (`changelog.yml` could be changed to be a pure HTML file, though, or one file for every version.)

If none of these libraries have proper multiplatform native support at the time this ticket is tackled, the task is to convert the listed files to another config file format like JSON or TOML and parse them as these files instead.

Some of these files are generated automatically, such as `credits_contributors.yml`, so some build scripts need to be adapted, too. Below some notes regarding each:

#### convert to TOML

- \+ well-human-readable format, easy to edit

- \- kotlinx-serialization plugin [`com.akuleshov7-ktoml-core`](https://github.com/akuleshov7/ktoml) is multiplatform but implementation is incomplete. In particular, "Array of Tables" feature is missing as the time of writing, which is necessary for `credits_translators.yml`

- \+ kotlinx-serialization plugin [`net.peanuuutz.tomlkt`](https://github.com/Peanuuutz/tomlkt) is multiplatform and is actually complete, looks well tested and has a useful interface. It's rather fresh at the time of writing, though (meaning, we don't know how well tested it is in production and how committed the author is to maintain it).

- \- the above is only marginally smaller (250KB) as `net.mamoe.yamlkt` (261KB) even though one would think that TOML is a much simpler markup language as YAML - maybe that isn't true

#### convert to JSON

- \+ less dependencies: `kotlinx-serialization-json` already is a dependency

- \- no comments possible. So, explanatory comments / docs cannot be included in these files

- still well enough human-readable, given that these files are not that often changed (`changelog.yml` could be changed to be a html file)

---

In general, at the time of writing, I think the best way forward is to simply exchange `kaml` with `yamlkt` and if this does not work, don't bother with TOML because implementation is equally "alpha" than the YAML plugins but use JSON for everything.

### PR DESCRIPTION
**Pull request by FloEdelmann**
* Fixes #5415
* Replaces and closes #5444

Using (multiplatform) [YamlKt](https://github.com/Him188/yamlkt) instead of converting the files to JSON turned out to be much easier than trying to convert all files to JSON for now.

We can still change config files from YAML to JSON in the future to eventually get rid of the YAML parser completely. We might want to wait for https://github.com/Kotlin/kotlinx.serialization/issues/2221 to allow comments in JSON files (and use the `.jsonc` file extension to reflect that). Trailing commas [are already allowed](https://togithub.com/Kotlin/kotlinx.serialization/pull/2480) with the `allowTrailingComma` option.

### CODE REVIEW

**Comment by westnordost** [comment]
Looks good to me! Do all the tests pass and did you test it? (I.e. look in the app at places where data parsed from Yaml should appear)

**Review by westnordost — APPROVED** [review]

**Comment by FloEdelmann** [comment]
Yesterday, I checked it in the app manually and everything seemed to work fine. But I didn't run the tests.

Now I did and the unit tests all pass, but the Android tests revealed that yamlkt has a problem with unquoted strings like `BEKB | BCBE`, which do indeed occur in country metadata (in this case it's a Swiss ATM operator).

So as predicted, the YAML format proves to add some difficulties :sweat_smile: 

The library we use to write the country metadata files (YamlBeans) has an option to quote strings, but it also quotes boolean values etc. then. So I'll look into writing the files with yamlkt now.

**Comment by FloEdelmann** [comment]
YamlKt is now also used (instead of YamlBeans) to generate the country metadata files, which works fine if the strings are always quoted. Otherwise, it splits e.g. `Tesla, Inc.` into two list items instead of one quoted one (see e.g. `AE.yml`). I opened https://github.com/Him188/yamlkt/issues/68.

Also, YamlKt has a stricter parser, which requires us to wrap e.g. regexes (which contain special characters like `[`) in single quotes, see https://github.com/streetcomplete/countrymetadata/pull/23.

Now the Android tests pass, except for the (unrelated) ones that are currently failing on `master`, too.

I also changed the `GetTranslatorCreditsTask` to use YamlKt instead of YamlBeans, but I am unable to test this because I don't have the access rights on POEditor. @westnordost, could you please run that task and check if it works fine?

**Comment by westnordost** [comment]
I've run the jobs as requested, didn't look at your other changes yet.

**Comment by westnordost** [comment]
Seeing that the library has some pretty obvious bugs and that the library hasn't seen a commit since 10 months despite some open bug reports, I think, let's just let this PR for a while wait and see if the issues will be fixed. If not, maybe the charleskorn library will gain proper multiplatform support. And finally if nothing is an option, the make-everything-JSON PR could be revived.

**Comment by FloEdelmann** [comment]
I opened another issue in their repository, let's see what happens: https://github.com/Him188/yamlkt/issues/69.

**Comment by westnordost** [comment]
Meanwhile, the author of [snakeyaml-engine-kmp](https://github.com/krzema12/snakeyaml-engine-kmp), a Kotlin multiplatform port of snakeyaml, stopped working on the [PR](https://github.com/charleskorn/kaml/pull/507) that would use snakeyaml-engine-kmp for all platforms of kaml.

It looks like only very little is missing to actually complete that PR and the PR in general is quite small. On the other hand, if the author of snakeyaml-engine-kmp has no to give up on finishing the PR, it looks to me as if either it is more work than it appears to finish it or he overall has no time to spare, in which case it it's unknown if we can expect snakeyaml-engine-kmp to continue to be maintained.

**Comment by krzema12** [comment]
Hi, the co-owner of snakeyaml-engine-kmp. Together with @sSemy we're committed to maintaining the KMP port of snakeyaml-engine. I stopped working on the mentioned PR mainly because I got a bit stuck with how okio works and how to port the JVM-specific API of kaml. It would be ideal if someone could pick up my effort on kaml side, then we'll be happy to keep snakeyaml-engine-kmp alive 🚀

**Comment by krzema12** [comment]
Sure, got it! I actually have another idea that may unblock you. My PR in kaml makes the JVM target use the KMP port of snakeyaml-engine. It may be better to make another step first: enable more targets in kaml thanks to snakeyaml-engine-kmp, and let the JVM target use snakeyaml-engine. Kaml already supports JS this way. It's not ideal long-term as little discrepancies may appear in behavior between JVM and the rest, but looking at how rarely snakeyaml-engine releases appear, I think it shouldn't be a big issue.

**Comment by westnordost** [comment]
Hmm, but this would mean to mostly duplicate the code currently in jsMain to iosMain. I think it is cleaner to move the code from jsMain to commonMain instead. Anyway, we are not in any particular hurry, we got a good amount of other things to do on our path to an eventual iOS port, so at the moment for me the most convenient action is to wait. (Not going to stop other contributors to jump in, though.)

(Anyway, IIRC correctly, I was a bit surprised that the kotlinx-serialization-json interface only works with from and to `String`, rather than from and to `InputStream`(java) / `Source`(okio) / `ByteArray`(kotlinx-io-core). I explained the apparent lack of API by that there is currently no standard multiplatform replacement of `InputStream` in Kotlin to myself.
So, from that point of view, I am surprised that kaml **does** offer an API for that, and depends on okio, apparently, which subsequently seems a bit un-clean to me. I.e. a parsing library should do parsing only, not do anything file-related)

**Comment by FloEdelmann** [comment]
Meanwhile, official kotlinx-serialization-json has started working on allowing comments: [Kotlin/kotlinx.serialization/#2221 (comment)](https://togithub.com/Kotlin/kotlinx.serialization/issues/2221#issuecomment-1979163452)

**Comment by westnordost** [comment]
No movement whatsoever on yamlkt repo, I guess it is unmaintained.

In the meantime, the mentioned PR in `kaml` was picked up by the other maintainer of `snakeyaml-engine-kmp`, merged and released. The only thing that seems to be missing now are to enable iOS (etc.) as a target over at `snakeyaml-engine-kmp` (which apparently also needs some tests/fixeing) and then also in `kaml`.

So, I would say this PR should definitely be closed, for it is clear that we will not use yamlkt, instead most likely we will keep using `kaml` or if there are unforeseen issues, kotlinx-serialization-json with comments.

**Comment by westnordost** [comment]
(If we settle on kaml, the stuff you did in this PR would still be nice - replacing the use of those other yaml-libraries in the buildscripts with just one, but I figure it would be most safe until we are 100% sure that we stay with yaml)

**Pull request closed without merging**
