### PR TITLE
Display name in undo dialog

### LINKED ISSUE #4767: Display name of amenity in Undo menu
**Use case**

Sometimes I want to undo a quest (from multi-level Undo menu), but if there have been several quests, I am unsure which quest refers to which object (e.g. several closely-spaced shops, cafes etc. and `opening_hours` quest), because Undo menu (as opposed to Quest itself) doesn't show amenity name/type. E.g.

small_Screenshot_20230126_180201_de westnordost streetcomplete small_Screenshot_20230126_180220_de westnordost streetcomplete

**Proposed Solution**

It would be great if the Undo entity when pressed would also contain name/type of the object on which the Quest was answered. E.g. in example above, second picture would also say _"Super Hrvoje (cafe)"_ below _"Are this opening hours still correct?"_. That would allow me to check if I'm undoing a right quest (instead of a closeby quest of same type!)

### PR DESCRIPTION
**Pull request by Helium314**
fix #4767 

This shows name and location label below the question in undo dialog, just like in the quest form.
I'm not sure how useful the location part is here, but there were no negative reactions on https://github.com/streetcomplete/StreetComplete/issues/4767#issuecomment-1407126969

### CODE REVIEW

**Comment by westnordost** [comment]
Code looks perfect. Did you test it?

**Review by westnordost — APPROVED** [review]

**Comment by westnordost** [comment]
I'll test it myself in a moment

**Comment by Helium314** [comment]
I did test it, and it it works, but I just found that for very long questions there is not enough space.

**Comment by Helium314** [comment]
Not sure how to handle this, maybe put icon and text in a sub-layout? I think neither text nor icon can be used for top/bottom constraints, as text may be much smaller or much larger than icon.

**Comment by westnordost** [comment]
What do you mean, it doesn't fit? Doesn't the dialog just get larger then?

**Comment by Helium314** [comment]
The `divider` is constrained to bottom of `icon`, and the icon top is constrained to bottom of `createdTimeText`. The `titleText` does not matter at all here.

You can try it in Android Studio by entering a very long `titleText` or `titleHintText`. Actually this could be an issue even without the added `titleHintText` in some languages with long texts.

**Comment by Helium314** [comment]
Looks like an [`Barrier`](https://stackoverflow.com/questions/47120035/constrainlayout-how-to-constrain-a-views-top-to-the-bottom-of-the-view-of-larg) does what I want, I'll try to get it working.

**Comment by Helium314** [comment]
The barrier below is straightforward, but I didn't get the barrier below `createdTimeText` to work...

**Comment by westnordost** [comment]
It's okay, I'll do it

**Pull request merged**
